//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.5
// source: github.com/s4wave/spacewave/sdk/world/world.proto

#include "world_srpc.pb.hpp"

namespace s4wave::world {

starpc::Error SRPCEngineResourceServiceClientImpl::GetEngineInfo(const s4wave::world::GetEngineInfoRequest& in, s4wave::world::GetEngineInfoResponse* out) {
  return cc_->ExecCall(service_id_, "GetEngineInfo", in, out);
}

starpc::Error SRPCEngineResourceServiceClientImpl::NewTransaction(const s4wave::world::NewTransactionRequest& in, s4wave::world::NewTransactionResponse* out) {
  return cc_->ExecCall(service_id_, "NewTransaction", in, out);
}

starpc::Error SRPCEngineResourceServiceClientImpl::GetSeqno(const s4wave::world::GetSeqnoRequest& in, s4wave::world::GetSeqnoResponse* out) {
  return cc_->ExecCall(service_id_, "GetSeqno", in, out);
}

starpc::Error SRPCEngineResourceServiceClientImpl::WaitSeqno(const s4wave::world::WaitSeqnoRequest& in, s4wave::world::WaitSeqnoResponse* out) {
  return cc_->ExecCall(service_id_, "WaitSeqno", in, out);
}

starpc::Error SRPCEngineResourceServiceClientImpl::BuildStorageCursor(const s4wave::world::BuildStorageCursorRequest& in, s4wave::world::BuildStorageCursorResponse* out) {
  return cc_->ExecCall(service_id_, "BuildStorageCursor", in, out);
}

starpc::Error SRPCEngineResourceServiceClientImpl::AccessWorldState(const s4wave::world::AccessWorldStateRequest& in, s4wave::world::AccessWorldStateResponse* out) {
  return cc_->ExecCall(service_id_, "AccessWorldState", in, out);
}

std::vector<std::string> SRPCEngineResourceServiceHandler::GetMethodIDs() const {
  return {
    "GetEngineInfo",
    "NewTransaction",
    "GetSeqno",
    "WaitSeqno",
    "BuildStorageCursor",
    "AccessWorldState",
  };
}

std::pair<bool, starpc::Error> SRPCEngineResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetEngineInfo") {
    s4wave::world::GetEngineInfoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetEngineInfoResponse resp;
    err = impl_->GetEngineInfo(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "NewTransaction") {
    s4wave::world::NewTransactionRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::NewTransactionResponse resp;
    err = impl_->NewTransaction(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "GetSeqno") {
    s4wave::world::GetSeqnoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetSeqnoResponse resp;
    err = impl_->GetSeqno(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "WaitSeqno") {
    s4wave::world::WaitSeqnoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::WaitSeqnoResponse resp;
    err = impl_->WaitSeqno(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "BuildStorageCursor") {
    s4wave::world::BuildStorageCursorRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::BuildStorageCursorResponse resp;
    err = impl_->BuildStorageCursor(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "AccessWorldState") {
    s4wave::world::AccessWorldStateRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::AccessWorldStateResponse resp;
    err = impl_->AccessWorldState(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::GetReadOnly(const s4wave::world::GetReadOnlyRequest& in, s4wave::world::GetReadOnlyResponse* out) {
  return cc_->ExecCall(service_id_, "GetReadOnly", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::GetSeqno(const s4wave::world::GetSeqnoRequest& in, s4wave::world::GetSeqnoResponse* out) {
  return cc_->ExecCall(service_id_, "GetSeqno", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::WaitSeqno(const s4wave::world::WaitSeqnoRequest& in, s4wave::world::WaitSeqnoResponse* out) {
  return cc_->ExecCall(service_id_, "WaitSeqno", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::BuildStorageCursor(const s4wave::world::BuildStorageCursorRequest& in, s4wave::world::BuildStorageCursorResponse* out) {
  return cc_->ExecCall(service_id_, "BuildStorageCursor", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::AccessWorldState(const s4wave::world::AccessWorldStateRequest& in, s4wave::world::AccessWorldStateResponse* out) {
  return cc_->ExecCall(service_id_, "AccessWorldState", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::CreateObject(const s4wave::world::CreateObjectRequest& in, s4wave::world::CreateObjectResponse* out) {
  return cc_->ExecCall(service_id_, "CreateObject", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::GetObject(const s4wave::world::GetObjectRequest& in, s4wave::world::GetObjectResponse* out) {
  return cc_->ExecCall(service_id_, "GetObject", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::IterateObjects(const s4wave::world::IterateObjectsRequest& in, s4wave::world::IterateObjectsResponse* out) {
  return cc_->ExecCall(service_id_, "IterateObjects", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::RenameObject(const s4wave::world::RenameObjectRequest& in, s4wave::world::RenameObjectResponse* out) {
  return cc_->ExecCall(service_id_, "RenameObject", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::DeleteObject(const s4wave::world::DeleteObjectRequest& in, s4wave::world::DeleteObjectResponse* out) {
  return cc_->ExecCall(service_id_, "DeleteObject", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::SetGraphQuad(const s4wave::world::SetGraphQuadRequest& in, s4wave::world::SetGraphQuadResponse* out) {
  return cc_->ExecCall(service_id_, "SetGraphQuad", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::DeleteGraphQuad(const s4wave::world::DeleteGraphQuadRequest& in, s4wave::world::DeleteGraphQuadResponse* out) {
  return cc_->ExecCall(service_id_, "DeleteGraphQuad", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::LookupGraphQuads(const s4wave::world::LookupGraphQuadsRequest& in, s4wave::world::LookupGraphQuadsResponse* out) {
  return cc_->ExecCall(service_id_, "LookupGraphQuads", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::ListObjectsWithType(const s4wave::world::ListObjectsWithTypeRequest& in, s4wave::world::ListObjectsWithTypeResponse* out) {
  return cc_->ExecCall(service_id_, "ListObjectsWithType", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::DeleteGraphObject(const s4wave::world::DeleteGraphObjectRequest& in, s4wave::world::DeleteGraphObjectResponse* out) {
  return cc_->ExecCall(service_id_, "DeleteGraphObject", in, out);
}

starpc::Error SRPCWorldStateResourceServiceClientImpl::ApplyWorldOp(const s4wave::world::ApplyWorldOpRequest& in, s4wave::world::ApplyWorldOpResponse* out) {
  return cc_->ExecCall(service_id_, "ApplyWorldOp", in, out);
}

std::vector<std::string> SRPCWorldStateResourceServiceHandler::GetMethodIDs() const {
  return {
    "GetReadOnly",
    "GetSeqno",
    "WaitSeqno",
    "BuildStorageCursor",
    "AccessWorldState",
    "CreateObject",
    "GetObject",
    "IterateObjects",
    "RenameObject",
    "DeleteObject",
    "SetGraphQuad",
    "DeleteGraphQuad",
    "LookupGraphQuads",
    "ListObjectsWithType",
    "DeleteGraphObject",
    "ApplyWorldOp",
  };
}

std::pair<bool, starpc::Error> SRPCWorldStateResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetReadOnly") {
    s4wave::world::GetReadOnlyRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetReadOnlyResponse resp;
    err = impl_->GetReadOnly(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "GetSeqno") {
    s4wave::world::GetSeqnoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetSeqnoResponse resp;
    err = impl_->GetSeqno(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "WaitSeqno") {
    s4wave::world::WaitSeqnoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::WaitSeqnoResponse resp;
    err = impl_->WaitSeqno(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "BuildStorageCursor") {
    s4wave::world::BuildStorageCursorRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::BuildStorageCursorResponse resp;
    err = impl_->BuildStorageCursor(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "AccessWorldState") {
    s4wave::world::AccessWorldStateRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::AccessWorldStateResponse resp;
    err = impl_->AccessWorldState(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "CreateObject") {
    s4wave::world::CreateObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::CreateObjectResponse resp;
    err = impl_->CreateObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "GetObject") {
    s4wave::world::GetObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetObjectResponse resp;
    err = impl_->GetObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "IterateObjects") {
    s4wave::world::IterateObjectsRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::IterateObjectsResponse resp;
    err = impl_->IterateObjects(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "RenameObject") {
    s4wave::world::RenameObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::RenameObjectResponse resp;
    err = impl_->RenameObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "DeleteObject") {
    s4wave::world::DeleteObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::DeleteObjectResponse resp;
    err = impl_->DeleteObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "SetGraphQuad") {
    s4wave::world::SetGraphQuadRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::SetGraphQuadResponse resp;
    err = impl_->SetGraphQuad(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "DeleteGraphQuad") {
    s4wave::world::DeleteGraphQuadRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::DeleteGraphQuadResponse resp;
    err = impl_->DeleteGraphQuad(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "LookupGraphQuads") {
    s4wave::world::LookupGraphQuadsRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::LookupGraphQuadsResponse resp;
    err = impl_->LookupGraphQuads(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "ListObjectsWithType") {
    s4wave::world::ListObjectsWithTypeRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::ListObjectsWithTypeResponse resp;
    err = impl_->ListObjectsWithType(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "DeleteGraphObject") {
    s4wave::world::DeleteGraphObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::DeleteGraphObjectResponse resp;
    err = impl_->DeleteGraphObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "ApplyWorldOp") {
    s4wave::world::ApplyWorldOpRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::ApplyWorldOpResponse resp;
    err = impl_->ApplyWorldOp(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

std::pair<std::unique_ptr<SRPCWatchWorldStateResourceService_WatchWorldStateClient>, starpc::Error> SRPCWatchWorldStateResourceServiceClientImpl::WatchWorldState(const s4wave::world::WatchWorldStateRequest& in) {
  auto [strm, err] = cc_->NewStream(service_id_, "WatchWorldState", &in);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  err = strm->CloseSend();
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCWatchWorldStateResourceService_WatchWorldStateClient>(std::move(strm)), starpc::Error::OK};
}

std::vector<std::string> SRPCWatchWorldStateResourceServiceHandler::GetMethodIDs() const {
  return {
    "WatchWorldState",
  };
}

std::pair<bool, starpc::Error> SRPCWatchWorldStateResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "WatchWorldState") {
    s4wave::world::WatchWorldStateRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    SRPCWatchWorldStateResourceService_WatchWorldStateStream serverStrm(strm);
    return {true, impl_->WatchWorldState(req, &serverStrm)};
  }

  return {false, starpc::Error::OK};
}

starpc::Error SRPCTxResourceServiceClientImpl::Commit(const s4wave::world::CommitRequest& in, s4wave::world::CommitResponse* out) {
  return cc_->ExecCall(service_id_, "Commit", in, out);
}

starpc::Error SRPCTxResourceServiceClientImpl::Discard(const s4wave::world::DiscardRequest& in, s4wave::world::DiscardResponse* out) {
  return cc_->ExecCall(service_id_, "Discard", in, out);
}

std::vector<std::string> SRPCTxResourceServiceHandler::GetMethodIDs() const {
  return {
    "Commit",
    "Discard",
  };
}

std::pair<bool, starpc::Error> SRPCTxResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "Commit") {
    s4wave::world::CommitRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::CommitResponse resp;
    err = impl_->Commit(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Discard") {
    s4wave::world::DiscardRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::DiscardResponse resp;
    err = impl_->Discard(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Err(const s4wave::world::ErrRequest& in, s4wave::world::ErrResponse* out) {
  return cc_->ExecCall(service_id_, "Err", in, out);
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Valid(const s4wave::world::ValidRequest& in, s4wave::world::ValidResponse* out) {
  return cc_->ExecCall(service_id_, "Valid", in, out);
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Key(const s4wave::world::KeyRequest& in, s4wave::world::KeyResponse* out) {
  return cc_->ExecCall(service_id_, "Key", in, out);
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Next(const s4wave::world::NextRequest& in, s4wave::world::NextResponse* out) {
  return cc_->ExecCall(service_id_, "Next", in, out);
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Seek(const s4wave::world::SeekRequest& in, s4wave::world::SeekResponse* out) {
  return cc_->ExecCall(service_id_, "Seek", in, out);
}

starpc::Error SRPCObjectIteratorResourceServiceClientImpl::Close(const s4wave::world::CloseRequest& in, s4wave::world::CloseResponse* out) {
  return cc_->ExecCall(service_id_, "Close", in, out);
}

std::vector<std::string> SRPCObjectIteratorResourceServiceHandler::GetMethodIDs() const {
  return {
    "Err",
    "Valid",
    "Key",
    "Next",
    "Seek",
    "Close",
  };
}

std::pair<bool, starpc::Error> SRPCObjectIteratorResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "Err") {
    s4wave::world::ErrRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::ErrResponse resp;
    err = impl_->Err(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Valid") {
    s4wave::world::ValidRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::ValidResponse resp;
    err = impl_->Valid(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Key") {
    s4wave::world::KeyRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::KeyResponse resp;
    err = impl_->Key(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Next") {
    s4wave::world::NextRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::NextResponse resp;
    err = impl_->Next(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Seek") {
    s4wave::world::SeekRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::SeekResponse resp;
    err = impl_->Seek(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Close") {
    s4wave::world::CloseRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::CloseResponse resp;
    err = impl_->Close(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::GetKey(const s4wave::world::GetKeyRequest& in, s4wave::world::GetKeyResponse* out) {
  return cc_->ExecCall(service_id_, "GetKey", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::GetRootRef(const s4wave::world::GetRootRefRequest& in, s4wave::world::GetRootRefResponse* out) {
  return cc_->ExecCall(service_id_, "GetRootRef", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::SetRootRef(const s4wave::world::SetRootRefRequest& in, s4wave::world::SetRootRefResponse* out) {
  return cc_->ExecCall(service_id_, "SetRootRef", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::AccessWorldState(const s4wave::world::AccessWorldStateRequest& in, s4wave::world::AccessWorldStateResponse* out) {
  return cc_->ExecCall(service_id_, "AccessWorldState", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::ApplyObjectOp(const s4wave::world::ApplyObjectOpRequest& in, s4wave::world::ApplyObjectOpResponse* out) {
  return cc_->ExecCall(service_id_, "ApplyObjectOp", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::IncrementRev(const s4wave::world::IncrementRevRequest& in, s4wave::world::IncrementRevResponse* out) {
  return cc_->ExecCall(service_id_, "IncrementRev", in, out);
}

starpc::Error SRPCObjectStateResourceServiceClientImpl::WaitRev(const s4wave::world::WaitRevRequest& in, s4wave::world::WaitRevResponse* out) {
  return cc_->ExecCall(service_id_, "WaitRev", in, out);
}

std::vector<std::string> SRPCObjectStateResourceServiceHandler::GetMethodIDs() const {
  return {
    "GetKey",
    "GetRootRef",
    "SetRootRef",
    "AccessWorldState",
    "ApplyObjectOp",
    "IncrementRev",
    "WaitRev",
  };
}

std::pair<bool, starpc::Error> SRPCObjectStateResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetKey") {
    s4wave::world::GetKeyRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetKeyResponse resp;
    err = impl_->GetKey(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "GetRootRef") {
    s4wave::world::GetRootRefRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::GetRootRefResponse resp;
    err = impl_->GetRootRef(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "SetRootRef") {
    s4wave::world::SetRootRefRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::SetRootRefResponse resp;
    err = impl_->SetRootRef(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "AccessWorldState") {
    s4wave::world::AccessWorldStateRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::AccessWorldStateResponse resp;
    err = impl_->AccessWorldState(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "ApplyObjectOp") {
    s4wave::world::ApplyObjectOpRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::ApplyObjectOpResponse resp;
    err = impl_->ApplyObjectOp(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "IncrementRev") {
    s4wave::world::IncrementRevRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::IncrementRevResponse resp;
    err = impl_->IncrementRev(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "WaitRev") {
    s4wave::world::WaitRevRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::WaitRevResponse resp;
    err = impl_->WaitRev(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

starpc::Error SRPCTypedObjectResourceServiceClientImpl::AccessTypedObject(const s4wave::world::AccessTypedObjectRequest& in, s4wave::world::AccessTypedObjectResponse* out) {
  return cc_->ExecCall(service_id_, "AccessTypedObject", in, out);
}

std::vector<std::string> SRPCTypedObjectResourceServiceHandler::GetMethodIDs() const {
  return {
    "AccessTypedObject",
  };
}

std::pair<bool, starpc::Error> SRPCTypedObjectResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "AccessTypedObject") {
    s4wave::world::AccessTypedObjectRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::world::AccessTypedObjectResponse resp;
    err = impl_->AccessTypedObject(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace s4wave::world
