#!/bin/sh
set -e

files=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$files" ]; then
	exit 0
fi

format_files=$(printf "%s\n" "$files" | grep -E '^((app|web|core|sdk|net)/.*\.(ts|tsx|js|html|css|scss)|[^/]+\.json|\.github/.*\.(json|yml)|\.oxfmtrc\.json|\.golangci\.yml|tsconfig.*\.json)$' || true)
if [ -n "$format_files" ]; then
	printf "%s\n" "$format_files" | xargs bunx oxfmt
	printf "%s\n" "$format_files" | xargs git add
fi

js_files=$(printf "%s\n" "$files" | grep -E '\.(js|mjs|ts|tsx)$' || true)
if [ -n "$js_files" ]; then
	printf "%s\n" "$js_files" | xargs bunx oxlint --no-error-on-unmatched-pattern
fi

go_files=$(printf "%s\n" "$files" | grep -E '\.go$' || true)
if [ -n "$go_files" ]; then
	printf "%s\n" "$go_files" | xargs gofmt -w
	printf "%s\n" "$go_files" | xargs git add

	go_pkgs=$(printf "%s\n" "$go_files" | xargs -n1 dirname | sort -u | sed 's#^#./#')
	go test -run '^$' $go_pkgs
fi

if printf "%s\n" "$files" | grep -Eq '^(go\.mod|go\.sum)$'; then
	go test -run '^$' ./...
fi
