//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.7
// source: github.com/s4wave/spacewave/sdk/configtype/registry/registry.proto

#include "registry_srpc.pb.hpp"

namespace s4wave::configtype::registry {

starpc::Error SRPCConfigTypeRegistryResourceServiceClientImpl::RegisterConfigType(const s4wave::configtype::registry::RegisterConfigTypeRequest& in, s4wave::configtype::registry::RegisterConfigTypeResponse* out) {
  return cc_->ExecCall(service_id_, "RegisterConfigType", in, out);
}

std::pair<std::unique_ptr<SRPCConfigTypeRegistryResourceService_WatchConfigTypesClient>, starpc::Error> SRPCConfigTypeRegistryResourceServiceClientImpl::WatchConfigTypes(const s4wave::configtype::registry::WatchConfigTypesRequest& in) {
  auto [strm, err] = cc_->NewStream(service_id_, "WatchConfigTypes", &in);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  err = strm->CloseSend();
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCConfigTypeRegistryResourceService_WatchConfigTypesClient>(std::move(strm)), starpc::Error::OK};
}

std::vector<std::string> SRPCConfigTypeRegistryResourceServiceHandler::GetMethodIDs() const {
  return {
    "RegisterConfigType",
    "WatchConfigTypes",
  };
}

std::pair<bool, starpc::Error> SRPCConfigTypeRegistryResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "RegisterConfigType") {
    s4wave::configtype::registry::RegisterConfigTypeRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::configtype::registry::RegisterConfigTypeResponse resp;
    err = impl_->RegisterConfigType(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "WatchConfigTypes") {
    s4wave::configtype::registry::WatchConfigTypesRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    SRPCConfigTypeRegistryResourceService_WatchConfigTypesStream serverStrm(strm);
    return {true, impl_->WatchConfigTypes(req, &serverStrm)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace s4wave::configtype::registry
