// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.15.1-0.20260716074925-e2a146f45568
// source: github.com/s4wave/spacewave/db/bucket/bucket.proto

package bucket

import (
	fmt "fmt"
	io "io"
	slices "slices"

	proto "github.com/aperturerobotics/controllerbus/controller/configset/proto"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	timestamppb "github.com/aperturerobotics/protobuf-go-lite/types/known/timestamppb"
	block "github.com/s4wave/spacewave/db/block"
	transform "github.com/s4wave/spacewave/db/block/transform"
)

// Config is a bucket configuration object.
type Config struct {
	unknownFields []byte
	// Id is the bucket identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Rev is the configuration rev.
	// increment by 1 on modification
	Rev uint32 `protobuf:"varint,2,opt,name=rev,proto3" json:"rev,omitempty"`
	// PutOpts are the default put options for the bucket.
	PutOpts *block.PutOpts `protobuf:"bytes,4,opt,name=put_opts,json=putOpts,proto3" json:"putOpts,omitempty"`
	// Lookup controls the lookup confiuration.
	Lookup *LookupConfig `protobuf:"bytes,5,opt,name=lookup,proto3" json:"lookup,omitempty"` // TODO: block size limit?
}

func (x *Config) Reset() {
	*x = Config{}
}

func (*Config) ProtoMessage() {}

func (x *Config) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Config) GetRev() uint32 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *Config) GetPutOpts() *block.PutOpts {
	if x != nil {
		return x.PutOpts
	}
	return nil
}

func (x *Config) GetLookup() *LookupConfig {
	if x != nil {
		return x.Lookup
	}
	return nil
}

// BucketInfo is general information about a bucket.
type BucketInfo struct {
	unknownFields []byte
	// Config contains the current latest bucket configuration.
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *BucketInfo) Reset() {
	*x = BucketInfo{}
}

func (*BucketInfo) ProtoMessage() {}

func (x *BucketInfo) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// LookupConfig configures the bucket behavior across multiple volumes.
type LookupConfig struct {
	unknownFields []byte
	// Disble indicates we should not service cross-volume calls against this
	// bucket.
	Disable bool `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	// Controller contains the lookup controller configuration.
	// If unset, will default to the node-default lookup controller.
	// If disabled, this field will be ignored.
	Controller *proto.ControllerConfig `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
}

func (x *LookupConfig) Reset() {
	*x = LookupConfig{}
}

func (*LookupConfig) ProtoMessage() {}

func (x *LookupConfig) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

func (x *LookupConfig) GetController() *proto.ControllerConfig {
	if x != nil {
		return x.Controller
	}
	return nil
}

// ApplyBucketConfigResult is the result of the ApplyBucketConfig directive.
type ApplyBucketConfigResult struct {
	unknownFields []byte
	// VolumeId is the volume ID for this apply event.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volumeId,omitempty"`
	// BucketId returns the bucket ID for this apply event.
	BucketId string `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucketId,omitempty"`
	// BucketConf returns the bucket configuration applied.
	BucketConf *Config `protobuf:"bytes,3,opt,name=bucket_conf,json=bucketConf,proto3" json:"bucketConf,omitempty"`
	// OldBucketConf returns the previous bucket configuration.
	OldBucketConf *Config `protobuf:"bytes,4,opt,name=old_bucket_conf,json=oldBucketConf,proto3" json:"oldBucketConf,omitempty"`
	// Timestamp returns the timestamp of the event.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Updated indicates if the value was updated.
	Updated bool `protobuf:"varint,6,opt,name=updated,proto3" json:"updated,omitempty"`
	// Error contains any error applying the value.
	// Note: all other values might be empty if this is set.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ApplyBucketConfigResult) Reset() {
	*x = ApplyBucketConfigResult{}
}

func (*ApplyBucketConfigResult) ProtoMessage() {}

func (x *ApplyBucketConfigResult) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ApplyBucketConfigResult) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *ApplyBucketConfigResult) GetBucketConf() *Config {
	if x != nil {
		return x.BucketConf
	}
	return nil
}

func (x *ApplyBucketConfigResult) GetOldBucketConf() *Config {
	if x != nil {
		return x.OldBucketConf
	}
	return nil
}

func (x *ApplyBucketConfigResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ApplyBucketConfigResult) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *ApplyBucketConfigResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ObjectRef is a reference that may contain a transformation config reference
// and/or a bucket ID change.
//
// protobuf-go-lite:disable-json
type ObjectRef struct {
	unknownFields []byte
	// RootRef is the root block ref.
	RootRef *block.BlockRef `protobuf:"bytes,1,opt,name=root_ref,json=rootRef,proto3" json:"rootRef,omitempty"`
	// BucketId is the bucket id, if switching buckets.
	// May be empty to indicate same bucket.
	BucketId string `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucketId,omitempty"`
	// TransformConfRef is the transformation configuration block ref.
	// Must be encoded with the same transformation config as the parent.
	// May be empty to indicate same conf as parent.
	TransformConfRef *block.BlockRef `protobuf:"bytes,3,opt,name=transform_conf_ref,json=transformConfRef,proto3" json:"transformConfRef,omitempty"`
	// TransformConf is an in-line transform configuration.
	TransformConf *transform.Config `protobuf:"bytes,4,opt,name=transform_conf,json=transformConf,proto3" json:"transformConf,omitempty"`
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) GetRootRef() *block.BlockRef {
	if x != nil {
		return x.RootRef
	}
	return nil
}

func (x *ObjectRef) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *ObjectRef) GetTransformConfRef() *block.BlockRef {
	if x != nil {
		return x.TransformConfRef
	}
	return nil
}

func (x *ObjectRef) GetTransformConf() *transform.Config {
	if x != nil {
		return x.TransformConf
	}
	return nil
}

// BucketOpArgs are common arguments for a bucket operation.
type BucketOpArgs struct {
	unknownFields []byte
	// BucketId is the bucket ID to operate on.
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucketId,omitempty"`
	// VolumeId is the volume ID to operate on.
	// If empty, will use the lookup controller.
	VolumeId string `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volumeId,omitempty"`
}

func (x *BucketOpArgs) Reset() {
	*x = BucketOpArgs{}
}

func (*BucketOpArgs) ProtoMessage() {}

func (x *BucketOpArgs) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketOpArgs) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (m *Config) CloneVT() *Config {
	if m == nil {
		return (*Config)(nil)
	}
	r := new(Config)
	r.Id = m.Id
	r.Rev = m.Rev
	r.PutOpts = protobuf_go_lite.CloneVTValue(m.PutOpts)
	r.Lookup = protobuf_go_lite.CloneVTValue(m.Lookup)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Config) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *BucketInfo) CloneVT() *BucketInfo {
	if m == nil {
		return (*BucketInfo)(nil)
	}
	r := new(BucketInfo)
	r.Config = protobuf_go_lite.CloneVTValue(m.Config)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *BucketInfo) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *LookupConfig) CloneVT() *LookupConfig {
	if m == nil {
		return (*LookupConfig)(nil)
	}
	r := new(LookupConfig)
	r.Disable = m.Disable
	r.Controller = protobuf_go_lite.CloneVTValue(m.Controller)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *LookupConfig) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *ApplyBucketConfigResult) CloneVT() *ApplyBucketConfigResult {
	if m == nil {
		return (*ApplyBucketConfigResult)(nil)
	}
	r := new(ApplyBucketConfigResult)
	r.VolumeId = m.VolumeId
	r.BucketId = m.BucketId
	r.Updated = m.Updated
	r.Error = m.Error
	r.BucketConf = protobuf_go_lite.CloneVTValue(m.BucketConf)
	r.OldBucketConf = protobuf_go_lite.CloneVTValue(m.OldBucketConf)
	r.Timestamp = protobuf_go_lite.CloneVTValue(m.Timestamp)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ApplyBucketConfigResult) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *ObjectRef) CloneVT() *ObjectRef {
	if m == nil {
		return (*ObjectRef)(nil)
	}
	r := new(ObjectRef)
	r.BucketId = m.BucketId
	r.RootRef = protobuf_go_lite.CloneVTValue(m.RootRef)
	r.TransformConfRef = protobuf_go_lite.CloneVTValue(m.TransformConfRef)
	r.TransformConf = protobuf_go_lite.CloneVTValue(m.TransformConf)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ObjectRef) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *BucketOpArgs) CloneVT() *BucketOpArgs {
	if m == nil {
		return (*BucketOpArgs)(nil)
	}
	r := new(BucketOpArgs)
	r.BucketId = m.BucketId
	r.VolumeId = m.VolumeId
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *BucketOpArgs) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Config) EqualVT(that *Config) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Id != that.Id {
		return false
	}
	if this.Rev != that.Rev {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.PutOpts, that.PutOpts) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Lookup, that.Lookup) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Config) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Config)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *BucketInfo) EqualVT(that *BucketInfo) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Config, that.Config) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *BucketInfo) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*BucketInfo)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *LookupConfig) EqualVT(that *LookupConfig) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Disable != that.Disable {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Controller, that.Controller) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LookupConfig) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*LookupConfig)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *ApplyBucketConfigResult) EqualVT(that *ApplyBucketConfigResult) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.VolumeId != that.VolumeId {
		return false
	}
	if this.BucketId != that.BucketId {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.BucketConf, that.BucketConf) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.OldBucketConf, that.OldBucketConf) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Timestamp, that.Timestamp) {
		return false
	}
	if this.Updated != that.Updated {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ApplyBucketConfigResult) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ApplyBucketConfigResult)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *ObjectRef) EqualVT(that *ObjectRef) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.RootRef, that.RootRef) {
		return false
	}
	if this.BucketId != that.BucketId {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.TransformConfRef, that.TransformConfRef) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.TransformConf, that.TransformConf) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ObjectRef) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ObjectRef)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *BucketOpArgs) EqualVT(that *BucketOpArgs) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.BucketId != that.BucketId {
		return false
	}
	if this.VolumeId != that.VolumeId {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *BucketOpArgs) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*BucketOpArgs)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Config message to JSON.
func (x *Config) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Id != "" || s.HasField("id") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("id")
		s.WriteString(x.Id)
	}
	if x.Rev != 0 || s.HasField("rev") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rev")
		s.WriteUint32(x.Rev)
	}
	if x.PutOpts != nil || s.HasField("putOpts") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("putOpts")
		x.PutOpts.MarshalProtoJSON(s.WithField("putOpts"))
	}
	if x.Lookup != nil || s.HasField("lookup") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("lookup")
		x.Lookup.MarshalProtoJSON(s.WithField("lookup"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Config to JSON.
func (x *Config) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Config message from JSON.
func (x *Config) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "id":
			s.AddField("id")
			x.Id = s.ReadString()
		case "rev":
			s.AddField("rev")
			x.Rev = s.ReadUint32()
		case "put_opts", "putOpts":
			if s.ReadNil() {
				x.PutOpts = nil
				return
			}
			x.PutOpts = &block.PutOpts{}
			x.PutOpts.UnmarshalProtoJSON(s.WithField("put_opts", true))
		case "lookup":
			if s.ReadNil() {
				x.Lookup = nil
				return
			}
			x.Lookup = &LookupConfig{}
			x.Lookup.UnmarshalProtoJSON(s.WithField("lookup", true))
		}
	})
}

// UnmarshalJSON unmarshals the Config from JSON.
func (x *Config) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the BucketInfo message to JSON.
func (x *BucketInfo) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Config != nil || s.HasField("config") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("config")
		x.Config.MarshalProtoJSON(s.WithField("config"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the BucketInfo to JSON.
func (x *BucketInfo) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the BucketInfo message from JSON.
func (x *BucketInfo) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "config":
			if s.ReadNil() {
				x.Config = nil
				return
			}
			x.Config = &Config{}
			x.Config.UnmarshalProtoJSON(s.WithField("config", true))
		}
	})
}

// UnmarshalJSON unmarshals the BucketInfo from JSON.
func (x *BucketInfo) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the LookupConfig message to JSON.
func (x *LookupConfig) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Disable || s.HasField("disable") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("disable")
		s.WriteBool(x.Disable)
	}
	if x.Controller != nil || s.HasField("controller") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("controller")
		x.Controller.MarshalProtoJSON(s.WithField("controller"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the LookupConfig to JSON.
func (x *LookupConfig) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the LookupConfig message from JSON.
func (x *LookupConfig) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "disable":
			s.AddField("disable")
			x.Disable = s.ReadBool()
		case "controller":
			if s.ReadNil() {
				x.Controller = nil
				return
			}
			x.Controller = &proto.ControllerConfig{}
			x.Controller.UnmarshalProtoJSON(s.WithField("controller", true))
		}
	})
}

// UnmarshalJSON unmarshals the LookupConfig from JSON.
func (x *LookupConfig) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ApplyBucketConfigResult message to JSON.
func (x *ApplyBucketConfigResult) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.VolumeId != "" || s.HasField("volumeId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("volumeId")
		s.WriteString(x.VolumeId)
	}
	if x.BucketId != "" || s.HasField("bucketId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("bucketId")
		s.WriteString(x.BucketId)
	}
	if x.BucketConf != nil || s.HasField("bucketConf") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("bucketConf")
		x.BucketConf.MarshalProtoJSON(s.WithField("bucketConf"))
	}
	if x.OldBucketConf != nil || s.HasField("oldBucketConf") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("oldBucketConf")
		x.OldBucketConf.MarshalProtoJSON(s.WithField("oldBucketConf"))
	}
	if x.Timestamp != nil || s.HasField("timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestamp")
		x.Timestamp.MarshalProtoJSON(s.WithField("timestamp"))
	}
	if x.Updated || s.HasField("updated") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("updated")
		s.WriteBool(x.Updated)
	}
	if x.Error != "" || s.HasField("error") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		s.WriteString(x.Error)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ApplyBucketConfigResult to JSON.
func (x *ApplyBucketConfigResult) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ApplyBucketConfigResult message from JSON.
func (x *ApplyBucketConfigResult) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "volume_id", "volumeId":
			s.AddField("volume_id")
			x.VolumeId = s.ReadString()
		case "bucket_id", "bucketId":
			s.AddField("bucket_id")
			x.BucketId = s.ReadString()
		case "bucket_conf", "bucketConf":
			if s.ReadNil() {
				x.BucketConf = nil
				return
			}
			x.BucketConf = &Config{}
			x.BucketConf.UnmarshalProtoJSON(s.WithField("bucket_conf", true))
		case "old_bucket_conf", "oldBucketConf":
			if s.ReadNil() {
				x.OldBucketConf = nil
				return
			}
			x.OldBucketConf = &Config{}
			x.OldBucketConf.UnmarshalProtoJSON(s.WithField("old_bucket_conf", true))
		case "timestamp":
			if s.ReadNil() {
				x.Timestamp = nil
				return
			}
			x.Timestamp = &timestamppb.Timestamp{}
			x.Timestamp.UnmarshalProtoJSON(s.WithField("timestamp", true))
		case "updated":
			s.AddField("updated")
			x.Updated = s.ReadBool()
		case "error":
			s.AddField("error")
			x.Error = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the ApplyBucketConfigResult from JSON.
func (x *ApplyBucketConfigResult) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the BucketOpArgs message to JSON.
func (x *BucketOpArgs) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.BucketId != "" || s.HasField("bucketId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("bucketId")
		s.WriteString(x.BucketId)
	}
	if x.VolumeId != "" || s.HasField("volumeId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("volumeId")
		s.WriteString(x.VolumeId)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the BucketOpArgs to JSON.
func (x *BucketOpArgs) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the BucketOpArgs message from JSON.
func (x *BucketOpArgs) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "bucket_id", "bucketId":
			s.AddField("bucket_id")
			x.BucketId = s.ReadString()
		case "volume_id", "volumeId":
			s.AddField("volume_id")
			x.VolumeId = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the BucketOpArgs from JSON.
func (x *BucketOpArgs) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Config) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Config) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Config) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Lookup != nil {
		size, err := m.Lookup.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.PutOpts != nil {
		size, err := m.PutOpts.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.Rev != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Rev))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Id)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BucketInfo) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BucketInfo) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *BucketInfo) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Config != nil {
		size, err := m.Config.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LookupConfig) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LookupConfig) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *LookupConfig) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Controller != nil {
		size, err := m.Controller.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Disable {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Disable)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ApplyBucketConfigResult) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplyBucketConfigResult) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ApplyBucketConfigResult) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Error) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
		i--
		dAtA[i] = 0x3a
	}
	if m.Updated {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Updated)
		i--
		dAtA[i] = 0x30
	}
	if m.Timestamp != nil {
		size, err := m.Timestamp.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.OldBucketConf != nil {
		size, err := m.OldBucketConf.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.BucketConf != nil {
		size, err := m.BucketConf.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BucketId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.BucketId)
		i--
		dAtA[i] = 0x12
	}
	if len(m.VolumeId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.VolumeId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectRef) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectRef) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ObjectRef) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.TransformConf != nil {
		size, err := m.TransformConf.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.TransformConfRef != nil {
		size, err := m.TransformConfRef.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BucketId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.BucketId)
		i--
		dAtA[i] = 0x12
	}
	if m.RootRef != nil {
		size, err := m.RootRef.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BucketOpArgs) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BucketOpArgs) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *BucketOpArgs) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.VolumeId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.VolumeId)
		i--
		dAtA[i] = 0x12
	}
	if len(m.BucketId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.BucketId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Config) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Id)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Rev)
	if m.PutOpts != nil {
		l = m.PutOpts.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Lookup != nil {
		l = m.Lookup.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *BucketInfo) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Config != nil {
		l = m.Config.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *LookupConfig) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Disable)
	if m.Controller != nil {
		l = m.Controller.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *ApplyBucketConfigResult) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.VolumeId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.BucketId)
	if m.BucketConf != nil {
		l = m.BucketConf.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.OldBucketConf != nil {
		l = m.OldBucketConf.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Timestamp != nil {
		l = m.Timestamp.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Updated)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Error)
	n += len(m.unknownFields)
	return n
}

func (m *ObjectRef) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RootRef != nil {
		l = m.RootRef.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.BucketId)
	if m.TransformConfRef != nil {
		l = m.TransformConfRef.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.TransformConf != nil {
		l = m.TransformConf.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *BucketOpArgs) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.BucketId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.VolumeId)
	n += len(m.unknownFields)
	return n
}

func (x *Config) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Config")
	if x.Id != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "id")
		protobuf_go_lite.TextWriteString(&sb, x.Id)
	}
	if x.Rev != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "rev")
		protobuf_go_lite.TextWriteUint(&sb, x.Rev)
	}
	if x.PutOpts != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "put_opts")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.PutOpts)
	}
	if x.Lookup != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "lookup")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Lookup)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Config) String() string {
	return x.MarshalProtoText()
}

func (x *BucketInfo) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "BucketInfo")
	if x.Config != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "config")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Config)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *BucketInfo) String() string {
	return x.MarshalProtoText()
}

func (x *LookupConfig) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "LookupConfig")
	if x.Disable != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "disable")
		protobuf_go_lite.TextWriteBool(&sb, x.Disable)
	}
	if x.Controller != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "controller")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Controller)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *LookupConfig) String() string {
	return x.MarshalProtoText()
}

func (x *ApplyBucketConfigResult) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ApplyBucketConfigResult")
	if x.VolumeId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "volume_id")
		protobuf_go_lite.TextWriteString(&sb, x.VolumeId)
	}
	if x.BucketId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bucket_id")
		protobuf_go_lite.TextWriteString(&sb, x.BucketId)
	}
	if x.BucketConf != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bucket_conf")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.BucketConf)
	}
	if x.OldBucketConf != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "old_bucket_conf")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.OldBucketConf)
	}
	if x.Timestamp != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Timestamp)
	}
	if x.Updated != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "updated")
		protobuf_go_lite.TextWriteBool(&sb, x.Updated)
	}
	if x.Error != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, x.Error)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ApplyBucketConfigResult) String() string {
	return x.MarshalProtoText()
}

func (x *ObjectRef) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ObjectRef")
	if x.RootRef != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "root_ref")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.RootRef)
	}
	if x.BucketId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bucket_id")
		protobuf_go_lite.TextWriteString(&sb, x.BucketId)
	}
	if x.TransformConfRef != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "transform_conf_ref")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.TransformConfRef)
	}
	if x.TransformConf != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "transform_conf")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.TransformConf)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ObjectRef) String() string {
	return x.MarshalProtoText()
}

func (x *BucketOpArgs) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "BucketOpArgs")
	if x.BucketId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bucket_id")
		protobuf_go_lite.TextWriteString(&sb, x.BucketId)
	}
	if x.VolumeId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "volume_id")
		protobuf_go_lite.TextWriteString(&sb, x.VolumeId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *BucketOpArgs) String() string {
	return x.MarshalProtoText()
}

func (m *Config) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Id = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rev", wireType)
			}
			m.Rev = 0
			m.Rev, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PutOpts", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.PutOpts == nil {
				m.PutOpts = &block.PutOpts{}
			}
			if err := m.PutOpts.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lookup", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Lookup == nil {
				m.Lookup = &LookupConfig{}
			}
			if err := m.Lookup.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *BucketInfo) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BucketInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BucketInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Config == nil {
				m.Config = &Config{}
			}
			if err := m.Config.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LookupConfig) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LookupConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LookupConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disable", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Disable = bool(v)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Controller == nil {
				m.Controller = &proto.ControllerConfig{}
			}
			if err := m.Controller.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ApplyBucketConfigResult) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplyBucketConfigResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplyBucketConfigResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.VolumeId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.BucketId = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketConf", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.BucketConf == nil {
				m.BucketConf = &Config{}
			}
			if err := m.BucketConf.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldBucketConf", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.OldBucketConf == nil {
				m.OldBucketConf = &Config{}
			}
			if err := m.OldBucketConf.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Timestamp == nil {
				m.Timestamp = &timestamppb.Timestamp{}
			}
			if err := m.Timestamp.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Updated = bool(v)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Error = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ObjectRef) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootRef", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.RootRef == nil {
				m.RootRef = &block.BlockRef{}
			}
			if err := m.RootRef.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.BucketId = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransformConfRef", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.TransformConfRef == nil {
				m.TransformConfRef = &block.BlockRef{}
			}
			if err := m.TransformConfRef.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransformConf", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.TransformConf == nil {
				m.TransformConf = &transform.Config{}
			}
			if err := m.TransformConf.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *BucketOpArgs) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BucketOpArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BucketOpArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.BucketId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.VolumeId = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
