package s4wave_wizard

// LookupObjectWizard returns the ObjectWizard definition for a type ID.
// Returns nil if the type is not a registered creatable type.
func LookupObjectWizard(typeID string) *ObjectWizard {
	for _, w := range ObjectWizards {
		if w.GetTypeId() == typeID {
			return w
		}
	}
	return nil
}

// ObjectWizards is the list of all registered object wizards.
var ObjectWizards = []*ObjectWizard{
	{
		TypeId:             "alpha/object-layout",
		DisplayName:        "Object Layout",
		Category:           "Layout",
		IconName:           "LuLayoutGrid",
		CreateOpId:         "space/world/init-object-layout",
		DefaultNamePattern: "Layout",
		KeyPrefix:          "object-layout/",
	},
	{
		TypeId:             "canvas",
		DisplayName:        "Canvas",
		Category:           "Layout",
		IconName:           "LuLayoutGrid",
		CreateOpId:         "space/world/init-canvas",
		DefaultNamePattern: "Canvas",
		KeyPrefix:          "canvas/",
	},
	{
		TypeId:             "unixfs/fs-node",
		DisplayName:        "Filesystem",
		Category:           "Files",
		IconName:           "LuHardDrive",
		CreateOpId:         "space/world/init-unixfs",
		DefaultNamePattern: "Files",
		KeyPrefix:          "fs/",
	},
	{
		TypeId:             "chat/channel",
		DisplayName:        "Chat Channel",
		Category:           "Chat",
		IconName:           "LuMessageSquare",
		CreateOpId:         "spacewave-chat/channel/create",
		DefaultNamePattern: "Chat",
		KeyPrefix:          "chat/channel/",
		Experimental:       true,
	},
	{
		TypeId:             "git/repo",
		DisplayName:        "Git Repository",
		Category:           "Files",
		IconName:           "LuGitBranch",
		CreateOpId:         "spacewave/git/repo/create",
		DefaultNamePattern: "Repository",
		KeyPrefix:          "git/repo/",
		Persistent:         true,
		WizardTypeId:       "wizard/git/repo",
	},
	{
		TypeId:             "forge/worker",
		DisplayName:        "Forge Worker",
		Category:           "Forge",
		IconName:           "LuCpu",
		CreateOpId:         "forge/worker/create",
		DefaultNamePattern: "Worker",
		KeyPrefix:          "forge/worker/",
		Persistent:         true,
		WizardTypeId:       "wizard/forge/worker",
		Experimental:       true,
	},
	{
		TypeId:             "spacewave/forge/dashboard",
		DisplayName:        "Forge Dashboard",
		Category:           "Forge",
		IconName:           "LuHammer",
		CreateOpId:         "spacewave/forge/dashboard/create",
		DefaultNamePattern: "Forge",
		KeyPrefix:          "forge/",
		Experimental:       true,
	},
	{
		TypeId:             "spacewave/computers",
		DisplayName:        "Computers",
		Category:           "Devices",
		IconName:           "LuMonitor",
		CreateOpId:         "spacewave/computers/create",
		DefaultNamePattern: "Computers",
		KeyPrefix:          "computers/",
		Experimental:       true,
	},
	{
		TypeId:             "spacewave/device",
		DisplayName:        "Add Device",
		Category:           "Devices",
		IconName:           "LuHardDrive",
		CreateOpId:         "spacewave/wizard/create",
		DefaultNamePattern: "Device",
		KeyPrefix:          "devices/",
		Persistent:         true,
		WizardTypeId:       "wizard/device/add",
	},
	{
		TypeId:             "forge/cluster",
		DisplayName:        "Forge Cluster",
		Category:           "Forge",
		IconName:           "LuServer",
		CreateOpId:         "forge/cluster/create",
		DefaultNamePattern: "Cluster",
		KeyPrefix:          "forge/cluster/",
		Persistent:         true,
		WizardTypeId:       "wizard/forge/cluster",
		Experimental:       true,
	},
	{
		TypeId:             "forge/job",
		DisplayName:        "Forge Job",
		Category:           "Forge",
		IconName:           "LuBriefcase",
		CreateOpId:         "spacewave/forge/job/create",
		DefaultNamePattern: "Job",
		KeyPrefix:          "forge/job/",
		Persistent:         true,
		WizardTypeId:       "wizard/forge/job",
		Experimental:       true,
	},
	{
		TypeId:             "forge/task",
		DisplayName:        "Forge Task",
		Category:           "Forge",
		IconName:           "LuListTodo",
		CreateOpId:         "spacewave/forge/task/create",
		DefaultNamePattern: "Task",
		KeyPrefix:          "forge/task/",
		Persistent:         true,
		WizardTypeId:       "wizard/forge/task",
		Experimental:       true,
	},
	{
		TypeId:             "vm/v86",
		DisplayName:        "V86 VM",
		Category:           "VM",
		IconName:           "LuMonitor",
		CreateOpId:         "vm/v86/create",
		DefaultNamePattern: "V86 VM",
		KeyPrefix:          "vm/v86/",
		Persistent:         true,
		WizardTypeId:       "wizard/vm/v86",
		Experimental:       true,
	},
}
