// @generated
// This file is @generated by prost-build.
/// Config configures the web-wasivm plugin host controller.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// MemoryLimitMb sets the WASM memory limit in MB. 0 = default (256).
    #[prost(uint32, tag="1")]
    pub memory_limit_mb: u32,
    /// Debug enables verbose kernel syscall logging.
    #[prost(bool, tag="2")]
    pub debug: bool,
}
// @@protoc_insertion_point(module)
