//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/s4wave/spacewave/core/forge/dashboard/dashboard.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto_2epb_2eh
#define github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto;
}  // extern "C"
namespace s4wave {
namespace forge {
namespace dashboard {
class CreateForgeDashboardOp;
struct CreateForgeDashboardOpDefaultTypeInternal;
extern CreateForgeDashboardOpDefaultTypeInternal _CreateForgeDashboardOp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CreateForgeDashboardOp_class_data_;
class ForgeDashboard;
struct ForgeDashboardDefaultTypeInternal;
extern ForgeDashboardDefaultTypeInternal _ForgeDashboard_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ForgeDashboard_class_data_;
class InitForgeQuickstartOp;
struct InitForgeQuickstartOpDefaultTypeInternal;
extern InitForgeQuickstartOpDefaultTypeInternal _InitForgeQuickstartOp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InitForgeQuickstartOp_class_data_;
class LinkForgeDashboardOp;
struct LinkForgeDashboardOpDefaultTypeInternal;
extern LinkForgeDashboardOpDefaultTypeInternal _LinkForgeDashboardOp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LinkForgeDashboardOp_class_data_;
}  // namespace dashboard
}  // namespace forge
}  // namespace s4wave
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace s4wave {
namespace forge {
namespace dashboard {

// ===================================================================


// -------------------------------------------------------------------

class LinkForgeDashboardOp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:s4wave.forge.dashboard.LinkForgeDashboardOp) */ {
 public:
  inline LinkForgeDashboardOp() : LinkForgeDashboardOp(nullptr) {}
  ~LinkForgeDashboardOp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LinkForgeDashboardOp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LinkForgeDashboardOp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LinkForgeDashboardOp(::google::protobuf::internal::ConstantInitialized);

  inline LinkForgeDashboardOp(const LinkForgeDashboardOp& from) : LinkForgeDashboardOp(nullptr, from) {}
  inline LinkForgeDashboardOp(LinkForgeDashboardOp&& from) noexcept
      : LinkForgeDashboardOp(nullptr, ::std::move(from)) {}
  inline LinkForgeDashboardOp& operator=(const LinkForgeDashboardOp& from) {
    CopyFrom(from);
    return *this;
  }
  inline LinkForgeDashboardOp& operator=(LinkForgeDashboardOp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LinkForgeDashboardOp& default_instance() {
    return *reinterpret_cast<const LinkForgeDashboardOp*>(
        &_LinkForgeDashboardOp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(LinkForgeDashboardOp& a, LinkForgeDashboardOp& b) { a.Swap(&b); }
  inline void Swap(LinkForgeDashboardOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LinkForgeDashboardOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LinkForgeDashboardOp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LinkForgeDashboardOp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LinkForgeDashboardOp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LinkForgeDashboardOp& from) { LinkForgeDashboardOp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LinkForgeDashboardOp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "s4wave.forge.dashboard.LinkForgeDashboardOp"; }

  explicit LinkForgeDashboardOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LinkForgeDashboardOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LinkForgeDashboardOp& from);
  LinkForgeDashboardOp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LinkForgeDashboardOp&& from) noexcept
      : LinkForgeDashboardOp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDashboardKeyFieldNumber = 1,
    kEntityKeyFieldNumber = 2,
  };
  // string dashboard_key = 1;
  void clear_dashboard_key() ;
  const ::std::string& dashboard_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dashboard_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dashboard_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dashboard_key();
  void set_allocated_dashboard_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dashboard_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dashboard_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dashboard_key();

  public:
  // string entity_key = 2;
  void clear_entity_key() ;
  const ::std::string& entity_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_entity_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_entity_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_entity_key();
  void set_allocated_entity_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_entity_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_entity_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_entity_key();

  public:
  // @@protoc_insertion_point(class_scope:s4wave.forge.dashboard.LinkForgeDashboardOp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 75,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LinkForgeDashboardOp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr dashboard_key_;
    ::google::protobuf::internal::ArenaStringPtr entity_key_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LinkForgeDashboardOp_class_data_;
// -------------------------------------------------------------------

class InitForgeQuickstartOp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:s4wave.forge.dashboard.InitForgeQuickstartOp) */ {
 public:
  inline InitForgeQuickstartOp() : InitForgeQuickstartOp(nullptr) {}
  ~InitForgeQuickstartOp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InitForgeQuickstartOp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InitForgeQuickstartOp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InitForgeQuickstartOp(::google::protobuf::internal::ConstantInitialized);

  inline InitForgeQuickstartOp(const InitForgeQuickstartOp& from) : InitForgeQuickstartOp(nullptr, from) {}
  inline InitForgeQuickstartOp(InitForgeQuickstartOp&& from) noexcept
      : InitForgeQuickstartOp(nullptr, ::std::move(from)) {}
  inline InitForgeQuickstartOp& operator=(const InitForgeQuickstartOp& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitForgeQuickstartOp& operator=(InitForgeQuickstartOp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitForgeQuickstartOp& default_instance() {
    return *reinterpret_cast<const InitForgeQuickstartOp*>(
        &_InitForgeQuickstartOp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(InitForgeQuickstartOp& a, InitForgeQuickstartOp& b) { a.Swap(&b); }
  inline void Swap(InitForgeQuickstartOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitForgeQuickstartOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitForgeQuickstartOp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InitForgeQuickstartOp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InitForgeQuickstartOp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InitForgeQuickstartOp& from) { InitForgeQuickstartOp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InitForgeQuickstartOp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "s4wave.forge.dashboard.InitForgeQuickstartOp"; }

  explicit InitForgeQuickstartOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InitForgeQuickstartOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InitForgeQuickstartOp& from);
  InitForgeQuickstartOp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InitForgeQuickstartOp&& from) noexcept
      : InitForgeQuickstartOp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLayoutKeyFieldNumber = 1,
    kDashboardKeyFieldNumber = 2,
    kClusterKeyFieldNumber = 3,
    kClusterNameFieldNumber = 4,
    kWorkerKeyFieldNumber = 6,
    kSessionPeerIdFieldNumber = 7,
    kTimestampFieldNumber = 5,
  };
  // string layout_key = 1;
  void clear_layout_key() ;
  const ::std::string& layout_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_layout_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_layout_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_layout_key();
  void set_allocated_layout_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_layout_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_layout_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_layout_key();

  public:
  // string dashboard_key = 2;
  void clear_dashboard_key() ;
  const ::std::string& dashboard_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dashboard_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dashboard_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dashboard_key();
  void set_allocated_dashboard_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dashboard_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dashboard_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dashboard_key();

  public:
  // string cluster_key = 3;
  void clear_cluster_key() ;
  const ::std::string& cluster_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cluster_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cluster_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cluster_key();
  void set_allocated_cluster_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cluster_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cluster_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cluster_key();

  public:
  // string cluster_name = 4;
  void clear_cluster_name() ;
  const ::std::string& cluster_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cluster_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cluster_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cluster_name();
  void set_allocated_cluster_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cluster_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cluster_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cluster_name();

  public:
  // string worker_key = 6;
  void clear_worker_key() ;
  const ::std::string& worker_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_worker_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_worker_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_worker_key();
  void set_allocated_worker_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_worker_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_worker_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_worker_key();

  public:
  // string session_peer_id = 7;
  void clear_session_peer_id() ;
  const ::std::string& session_peer_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_peer_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_peer_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_peer_id();
  void set_allocated_session_peer_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_peer_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_peer_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_peer_id();

  public:
  // .google.protobuf.Timestamp timestamp = 5;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_timestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // @@protoc_insertion_point(class_scope:s4wave.forge.dashboard.InitForgeQuickstartOp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   1, 124,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InitForgeQuickstartOp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr layout_key_;
    ::google::protobuf::internal::ArenaStringPtr dashboard_key_;
    ::google::protobuf::internal::ArenaStringPtr cluster_key_;
    ::google::protobuf::internal::ArenaStringPtr cluster_name_;
    ::google::protobuf::internal::ArenaStringPtr worker_key_;
    ::google::protobuf::internal::ArenaStringPtr session_peer_id_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InitForgeQuickstartOp_class_data_;
// -------------------------------------------------------------------

class ForgeDashboard final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:s4wave.forge.dashboard.ForgeDashboard) */ {
 public:
  inline ForgeDashboard() : ForgeDashboard(nullptr) {}
  ~ForgeDashboard() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ForgeDashboard* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ForgeDashboard));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ForgeDashboard(::google::protobuf::internal::ConstantInitialized);

  inline ForgeDashboard(const ForgeDashboard& from) : ForgeDashboard(nullptr, from) {}
  inline ForgeDashboard(ForgeDashboard&& from) noexcept
      : ForgeDashboard(nullptr, ::std::move(from)) {}
  inline ForgeDashboard& operator=(const ForgeDashboard& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForgeDashboard& operator=(ForgeDashboard&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ForgeDashboard& default_instance() {
    return *reinterpret_cast<const ForgeDashboard*>(
        &_ForgeDashboard_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ForgeDashboard& a, ForgeDashboard& b) { a.Swap(&b); }
  inline void Swap(ForgeDashboard* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForgeDashboard* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForgeDashboard* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ForgeDashboard>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ForgeDashboard& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ForgeDashboard& from) { ForgeDashboard::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ForgeDashboard* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "s4wave.forge.dashboard.ForgeDashboard"; }

  explicit ForgeDashboard(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ForgeDashboard(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ForgeDashboard& from);
  ForgeDashboard(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ForgeDashboard&& from) noexcept
      : ForgeDashboard(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kCreatedAtFieldNumber = 2,
  };
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .google.protobuf.Timestamp created_at = 2;
  bool has_created_at() const;
  void clear_created_at() ;
  const ::google::protobuf::Timestamp& created_at() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_created_at();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_created_at();
  void set_allocated_created_at(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_created_at(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_created_at();

  private:
  const ::google::protobuf::Timestamp& _internal_created_at() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_created_at();

  public:
  // @@protoc_insertion_point(class_scope:s4wave.forge.dashboard.ForgeDashboard)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 50,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ForgeDashboard& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE created_at_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ForgeDashboard_class_data_;
// -------------------------------------------------------------------

class CreateForgeDashboardOp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:s4wave.forge.dashboard.CreateForgeDashboardOp) */ {
 public:
  inline CreateForgeDashboardOp() : CreateForgeDashboardOp(nullptr) {}
  ~CreateForgeDashboardOp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateForgeDashboardOp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateForgeDashboardOp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CreateForgeDashboardOp(::google::protobuf::internal::ConstantInitialized);

  inline CreateForgeDashboardOp(const CreateForgeDashboardOp& from) : CreateForgeDashboardOp(nullptr, from) {}
  inline CreateForgeDashboardOp(CreateForgeDashboardOp&& from) noexcept
      : CreateForgeDashboardOp(nullptr, ::std::move(from)) {}
  inline CreateForgeDashboardOp& operator=(const CreateForgeDashboardOp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateForgeDashboardOp& operator=(CreateForgeDashboardOp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateForgeDashboardOp& default_instance() {
    return *reinterpret_cast<const CreateForgeDashboardOp*>(
        &_CreateForgeDashboardOp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CreateForgeDashboardOp& a, CreateForgeDashboardOp& b) { a.Swap(&b); }
  inline void Swap(CreateForgeDashboardOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateForgeDashboardOp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateForgeDashboardOp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateForgeDashboardOp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateForgeDashboardOp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateForgeDashboardOp& from) { CreateForgeDashboardOp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateForgeDashboardOp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "s4wave.forge.dashboard.CreateForgeDashboardOp"; }

  explicit CreateForgeDashboardOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateForgeDashboardOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateForgeDashboardOp& from);
  CreateForgeDashboardOp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateForgeDashboardOp&& from) noexcept
      : CreateForgeDashboardOp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectKeyFieldNumber = 1,
    kNameFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // string object_key = 1;
  void clear_object_key() ;
  const ::std::string& object_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_object_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_object_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_object_key();
  void set_allocated_object_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_object_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_object_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_object_key();

  public:
  // string name = 2;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .google.protobuf.Timestamp timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_timestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // @@protoc_insertion_point(class_scope:s4wave.forge.dashboard.CreateForgeDashboardOp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 68,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateForgeDashboardOp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr object_key_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CreateForgeDashboardOp_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ForgeDashboard

// string name = 1;
inline void ForgeDashboard::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ForgeDashboard::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.ForgeDashboard.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ForgeDashboard::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.ForgeDashboard.name)
}
inline ::std::string* PROTOBUF_NONNULL ForgeDashboard::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.ForgeDashboard.name)
  return _s;
}
inline const ::std::string& ForgeDashboard::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ForgeDashboard::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ForgeDashboard::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ForgeDashboard::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.ForgeDashboard.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void ForgeDashboard::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.ForgeDashboard.name)
}

// .google.protobuf.Timestamp created_at = 2;
inline bool ForgeDashboard::has_created_at() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.created_at_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& ForgeDashboard::_internal_created_at() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.created_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& ForgeDashboard::created_at() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.ForgeDashboard.created_at)
  return _internal_created_at();
}
inline void ForgeDashboard::unsafe_arena_set_allocated_created_at(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.created_at_);
  }
  _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:s4wave.forge.dashboard.ForgeDashboard.created_at)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE ForgeDashboard::release_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::google::protobuf::Timestamp* released = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE ForgeDashboard::unsafe_arena_release_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.ForgeDashboard.created_at)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::google::protobuf::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL ForgeDashboard::_internal_mutable_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.created_at_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.created_at_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL ForgeDashboard::mutable_created_at()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::google::protobuf::Timestamp* _msg = _internal_mutable_created_at();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.ForgeDashboard.created_at)
  return _msg;
}
inline void ForgeDashboard::set_allocated_created_at(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.created_at_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.ForgeDashboard.created_at)
}

// -------------------------------------------------------------------

// CreateForgeDashboardOp

// string object_key = 1;
inline void CreateForgeDashboardOp::clear_object_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CreateForgeDashboardOp::object_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.CreateForgeDashboardOp.object_key)
  return _internal_object_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateForgeDashboardOp::set_object_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.object_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.CreateForgeDashboardOp.object_key)
}
inline ::std::string* PROTOBUF_NONNULL CreateForgeDashboardOp::mutable_object_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_object_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.CreateForgeDashboardOp.object_key)
  return _s;
}
inline const ::std::string& CreateForgeDashboardOp::_internal_object_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.object_key_.Get();
}
inline void CreateForgeDashboardOp::_internal_set_object_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateForgeDashboardOp::_internal_mutable_object_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.object_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateForgeDashboardOp::release_object_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.CreateForgeDashboardOp.object_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.object_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.object_key_.Set("", GetArena());
  }
  return released;
}
inline void CreateForgeDashboardOp::set_allocated_object_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.object_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.object_key_.IsDefault()) {
    _impl_.object_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.CreateForgeDashboardOp.object_key)
}

// string name = 2;
inline void CreateForgeDashboardOp::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CreateForgeDashboardOp::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.CreateForgeDashboardOp.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateForgeDashboardOp::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.CreateForgeDashboardOp.name)
}
inline ::std::string* PROTOBUF_NONNULL CreateForgeDashboardOp::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.CreateForgeDashboardOp.name)
  return _s;
}
inline const ::std::string& CreateForgeDashboardOp::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void CreateForgeDashboardOp::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateForgeDashboardOp::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateForgeDashboardOp::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.CreateForgeDashboardOp.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void CreateForgeDashboardOp::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.CreateForgeDashboardOp.name)
}

// .google.protobuf.Timestamp timestamp = 3;
inline bool CreateForgeDashboardOp::has_timestamp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& CreateForgeDashboardOp::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& CreateForgeDashboardOp::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.CreateForgeDashboardOp.timestamp)
  return _internal_timestamp();
}
inline void CreateForgeDashboardOp::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:s4wave.forge.dashboard.CreateForgeDashboardOp.timestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE CreateForgeDashboardOp::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE CreateForgeDashboardOp::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.CreateForgeDashboardOp.timestamp)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL CreateForgeDashboardOp::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL CreateForgeDashboardOp::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.CreateForgeDashboardOp.timestamp)
  return _msg;
}
inline void CreateForgeDashboardOp::set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.CreateForgeDashboardOp.timestamp)
}

// -------------------------------------------------------------------

// LinkForgeDashboardOp

// string dashboard_key = 1;
inline void LinkForgeDashboardOp::clear_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dashboard_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& LinkForgeDashboardOp::dashboard_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.LinkForgeDashboardOp.dashboard_key)
  return _internal_dashboard_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void LinkForgeDashboardOp::set_dashboard_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.dashboard_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.LinkForgeDashboardOp.dashboard_key)
}
inline ::std::string* PROTOBUF_NONNULL LinkForgeDashboardOp::mutable_dashboard_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_dashboard_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.LinkForgeDashboardOp.dashboard_key)
  return _s;
}
inline const ::std::string& LinkForgeDashboardOp::_internal_dashboard_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dashboard_key_.Get();
}
inline void LinkForgeDashboardOp::_internal_set_dashboard_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dashboard_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL LinkForgeDashboardOp::_internal_mutable_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dashboard_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE LinkForgeDashboardOp::release_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.LinkForgeDashboardOp.dashboard_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.dashboard_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dashboard_key_.Set("", GetArena());
  }
  return released;
}
inline void LinkForgeDashboardOp::set_allocated_dashboard_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.dashboard_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dashboard_key_.IsDefault()) {
    _impl_.dashboard_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.LinkForgeDashboardOp.dashboard_key)
}

// string entity_key = 2;
inline void LinkForgeDashboardOp::clear_entity_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entity_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& LinkForgeDashboardOp::entity_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.LinkForgeDashboardOp.entity_key)
  return _internal_entity_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void LinkForgeDashboardOp::set_entity_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.entity_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.LinkForgeDashboardOp.entity_key)
}
inline ::std::string* PROTOBUF_NONNULL LinkForgeDashboardOp::mutable_entity_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_entity_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.LinkForgeDashboardOp.entity_key)
  return _s;
}
inline const ::std::string& LinkForgeDashboardOp::_internal_entity_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entity_key_.Get();
}
inline void LinkForgeDashboardOp::_internal_set_entity_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entity_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL LinkForgeDashboardOp::_internal_mutable_entity_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.entity_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE LinkForgeDashboardOp::release_entity_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.LinkForgeDashboardOp.entity_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.entity_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.entity_key_.Set("", GetArena());
  }
  return released;
}
inline void LinkForgeDashboardOp::set_allocated_entity_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.entity_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.entity_key_.IsDefault()) {
    _impl_.entity_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.LinkForgeDashboardOp.entity_key)
}

// -------------------------------------------------------------------

// InitForgeQuickstartOp

// string layout_key = 1;
inline void InitForgeQuickstartOp::clear_layout_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.layout_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& InitForgeQuickstartOp::layout_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.layout_key)
  return _internal_layout_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_layout_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.layout_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.layout_key)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_layout_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_layout_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.layout_key)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_layout_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.layout_key_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_layout_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.layout_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_layout_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.layout_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_layout_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.layout_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.layout_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.layout_key_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_layout_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.layout_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.layout_key_.IsDefault()) {
    _impl_.layout_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.layout_key)
}

// string dashboard_key = 2;
inline void InitForgeQuickstartOp::clear_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dashboard_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& InitForgeQuickstartOp::dashboard_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.dashboard_key)
  return _internal_dashboard_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_dashboard_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.dashboard_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.dashboard_key)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_dashboard_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_dashboard_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.dashboard_key)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_dashboard_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dashboard_key_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_dashboard_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dashboard_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dashboard_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_dashboard_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.dashboard_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.dashboard_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dashboard_key_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_dashboard_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.dashboard_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dashboard_key_.IsDefault()) {
    _impl_.dashboard_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.dashboard_key)
}

// string cluster_key = 3;
inline void InitForgeQuickstartOp::clear_cluster_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& InitForgeQuickstartOp::cluster_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_key)
  return _internal_cluster_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_cluster_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.cluster_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_key)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_cluster_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_cluster_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_key)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_cluster_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cluster_key_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_cluster_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_cluster_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cluster_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_cluster_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.cluster_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cluster_key_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_cluster_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.cluster_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cluster_key_.IsDefault()) {
    _impl_.cluster_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_key)
}

// string cluster_name = 4;
inline void InitForgeQuickstartOp::clear_cluster_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& InitForgeQuickstartOp::cluster_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_name)
  return _internal_cluster_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_cluster_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.cluster_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_name)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_cluster_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_cluster_name();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_name)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_cluster_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cluster_name_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_cluster_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_cluster_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cluster_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_cluster_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.cluster_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cluster_name_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_cluster_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.cluster_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cluster_name_.IsDefault()) {
    _impl_.cluster_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.cluster_name)
}

// .google.protobuf.Timestamp timestamp = 5;
inline bool InitForgeQuickstartOp::has_timestamp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& InitForgeQuickstartOp::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& InitForgeQuickstartOp::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.timestamp)
  return _internal_timestamp();
}
inline void InitForgeQuickstartOp::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.timestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE InitForgeQuickstartOp::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.timestamp)

  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.timestamp)
  return _msg;
}
inline void InitForgeQuickstartOp::set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.timestamp)
}

// string worker_key = 6;
inline void InitForgeQuickstartOp::clear_worker_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worker_key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& InitForgeQuickstartOp::worker_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.worker_key)
  return _internal_worker_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_worker_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.worker_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.worker_key)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_worker_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_worker_key();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.worker_key)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_worker_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.worker_key_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_worker_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worker_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_worker_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.worker_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_worker_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.worker_key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.worker_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.worker_key_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_worker_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.worker_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.worker_key_.IsDefault()) {
    _impl_.worker_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.worker_key)
}

// string session_peer_id = 7;
inline void InitForgeQuickstartOp::clear_session_peer_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_peer_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& InitForgeQuickstartOp::session_peer_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:s4wave.forge.dashboard.InitForgeQuickstartOp.session_peer_id)
  return _internal_session_peer_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InitForgeQuickstartOp::set_session_peer_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.session_peer_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:s4wave.forge.dashboard.InitForgeQuickstartOp.session_peer_id)
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::mutable_session_peer_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_session_peer_id();
  // @@protoc_insertion_point(field_mutable:s4wave.forge.dashboard.InitForgeQuickstartOp.session_peer_id)
  return _s;
}
inline const ::std::string& InitForgeQuickstartOp::_internal_session_peer_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_peer_id_.Get();
}
inline void InitForgeQuickstartOp::_internal_set_session_peer_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_peer_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InitForgeQuickstartOp::_internal_mutable_session_peer_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_peer_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InitForgeQuickstartOp::release_session_peer_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:s4wave.forge.dashboard.InitForgeQuickstartOp.session_peer_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.session_peer_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_peer_id_.Set("", GetArena());
  }
  return released;
}
inline void InitForgeQuickstartOp::set_allocated_session_peer_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.session_peer_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_peer_id_.IsDefault()) {
    _impl_.session_peer_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:s4wave.forge.dashboard.InitForgeQuickstartOp.session_peer_id)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dashboard
}  // namespace forge
}  // namespace s4wave


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fs4wave_2fspacewave_2fcore_2fforge_2fdashboard_2fdashboard_2eproto_2epb_2eh
