//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.7
// source: github.com/s4wave/spacewave/bldr/plugin/plugin.proto

#include "plugin_srpc.pb.hpp"

namespace bldr::plugin {

starpc::Error SRPCPluginHostClientImpl::GetPluginInfo(const bldr::plugin::GetPluginInfoRequest& in, bldr::plugin::GetPluginInfoResponse* out) {
  return cc_->ExecCall(service_id_, "GetPluginInfo", in, out);
}

std::pair<std::unique_ptr<SRPCPluginHost_ExecControllerClient>, starpc::Error> SRPCPluginHostClientImpl::ExecController(const controller::exec::ExecControllerRequest& in) {
  auto [strm, err] = cc_->NewStream(service_id_, "ExecController", &in);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  err = strm->CloseSend();
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCPluginHost_ExecControllerClient>(std::move(strm)), starpc::Error::OK};
}

std::pair<std::unique_ptr<SRPCPluginHost_LoadPluginClient>, starpc::Error> SRPCPluginHostClientImpl::LoadPlugin(const bldr::plugin::LoadPluginRequest& in) {
  auto [strm, err] = cc_->NewStream(service_id_, "LoadPlugin", &in);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  err = strm->CloseSend();
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCPluginHost_LoadPluginClient>(std::move(strm)), starpc::Error::OK};
}

std::pair<std::unique_ptr<SRPCPluginHost_PluginRpcClient>, starpc::Error> SRPCPluginHostClientImpl::PluginRpc() {
  auto [strm, err] = cc_->NewStream(service_id_, "PluginRpc", nullptr);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCPluginHost_PluginRpcClient>(std::move(strm)), starpc::Error::OK};
}

std::pair<std::unique_ptr<SRPCPluginHost_PluginFsRpcClient>, starpc::Error> SRPCPluginHostClientImpl::PluginFsRpc() {
  auto [strm, err] = cc_->NewStream(service_id_, "PluginFsRpc", nullptr);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCPluginHost_PluginFsRpcClient>(std::move(strm)), starpc::Error::OK};
}

std::vector<std::string> SRPCPluginHostHandler::GetMethodIDs() const {
  return {
    "GetPluginInfo",
    "ExecController",
    "LoadPlugin",
    "PluginRpc",
    "PluginFsRpc",
  };
}

std::pair<bool, starpc::Error> SRPCPluginHostHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetPluginInfo") {
    bldr::plugin::GetPluginInfoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    bldr::plugin::GetPluginInfoResponse resp;
    err = impl_->GetPluginInfo(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "ExecController") {
    controller::exec::ExecControllerRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    SRPCPluginHost_ExecControllerStream serverStrm(strm);
    return {true, impl_->ExecController(req, &serverStrm)};
  } else if (method_id == "LoadPlugin") {
    bldr::plugin::LoadPluginRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    SRPCPluginHost_LoadPluginStream serverStrm(strm);
    return {true, impl_->LoadPlugin(req, &serverStrm)};
  } else if (method_id == "PluginRpc") {
    SRPCPluginHost_PluginRpcStream bidiStrm(strm);
    return {true, impl_->PluginRpc(&bidiStrm)};
  } else if (method_id == "PluginFsRpc") {
    SRPCPluginHost_PluginFsRpcStream bidiStrm(strm);
    return {true, impl_->PluginFsRpc(&bidiStrm)};
  }

  return {false, starpc::Error::OK};
}

std::pair<std::unique_ptr<SRPCPlugin_PluginRpcClient>, starpc::Error> SRPCPluginClientImpl::PluginRpc() {
  auto [strm, err] = cc_->NewStream(service_id_, "PluginRpc", nullptr);
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::make_unique<SRPCPlugin_PluginRpcClient>(std::move(strm)), starpc::Error::OK};
}

std::vector<std::string> SRPCPluginHandler::GetMethodIDs() const {
  return {
    "PluginRpc",
  };
}

std::pair<bool, starpc::Error> SRPCPluginHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "PluginRpc") {
    SRPCPlugin_PluginRpcStream bidiStrm(strm);
    return {true, impl_->PluginRpc(&bidiStrm)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace bldr::plugin
