// @generated by protoc-gen-es v1.8.0 with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/hydra/object/rpc/object.proto (package object.rpc, syntax proto3)
/* eslint-disable */

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Message, proto3 } from '@bufbuild/protobuf'

/**
 * RmObjectStoreRequest requests to remove an object store and all contents.
 *
 * @generated from message object.rpc.RmObjectStoreRequest
 */
export class RmObjectStoreRequest extends Message<RmObjectStoreRequest> {
  /**
   * ObjectStoreId is the object store identifier to remove.
   *
   * @generated from field: string object_store_id = 1;
   */
  objectStoreId = ''

  constructor(data?: PartialMessage<RmObjectStoreRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'object.rpc.RmObjectStoreRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'object_store_id',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RmObjectStoreRequest {
    return new RmObjectStoreRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RmObjectStoreRequest {
    return new RmObjectStoreRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RmObjectStoreRequest {
    return new RmObjectStoreRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: RmObjectStoreRequest | PlainMessage<RmObjectStoreRequest> | undefined,
    b: RmObjectStoreRequest | PlainMessage<RmObjectStoreRequest> | undefined,
  ): boolean {
    return proto3.util.equals(RmObjectStoreRequest, a, b)
  }
}

/**
 * RmObjectStoreResponse is the response to removing an object store.
 *
 * @generated from message object.rpc.RmObjectStoreResponse
 */
export class RmObjectStoreResponse extends Message<RmObjectStoreResponse> {
  /**
   * Error is any error removing the object store.
   * Will be empty if the store did not exist.
   *
   * @generated from field: string error = 1;
   */
  error = ''

  constructor(data?: PartialMessage<RmObjectStoreResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'object.rpc.RmObjectStoreResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'error', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RmObjectStoreResponse {
    return new RmObjectStoreResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RmObjectStoreResponse {
    return new RmObjectStoreResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RmObjectStoreResponse {
    return new RmObjectStoreResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: RmObjectStoreResponse | PlainMessage<RmObjectStoreResponse> | undefined,
    b: RmObjectStoreResponse | PlainMessage<RmObjectStoreResponse> | undefined,
  ): boolean {
    return proto3.util.equals(RmObjectStoreResponse, a, b)
  }
}
