syntax = "proto3";
package store.kvkey;

// Config is key/value key configuration.
message Config {
  // Prefix is the prefix applied to all keys.
  // Default: h/
  bytes prefix = 1;
  // BucketConfigPrefix is the prefix applied to bucket configs.
  // Default: bkt/c/
  bytes bucket_config_prefix = 2;
  // PeerPrivKey is the key to use for the peer private key.
  // Default: priv
  bytes peer_priv_key = 3;
  // BlockPrefix is the prefix applied to block hashes.
  // Default: b/
  bytes block_prefix = 5;
  // ObjectStorePrefix is the prefix applied to object stores.
  // Default: objs/
  bytes object_store_prefix = 6;

  // reserved 4
  // reserved: 7-9 message queue prefixes
}
