// @generated by protoc-gen-es v1.9.0 with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/hydra/block/store/rpc/server/config.proto (package block.store.rpc.server, syntax proto3)
/* eslint-disable */

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Message, proto3 } from '@bufbuild/protobuf'
import { HashType } from '@go/github.com/aperturerobotics/bifrost/hash/hash_pb.js'

/**
 * Config configures the block store rpc server.
 *
 * @generated from message block.store.rpc.server.Config
 */
export class Config extends Message<Config> {
  /**
   * BucketId is the bucket id to lookup on the bus.
   *
   * @generated from field: string bucket_id = 1;
   */
  bucketId = ''

  /**
   * VolumeId is the volume id to read/write from.
   * If unset, uses the BucketLookup API to lookup blocks.
   * Can be empty.
   *
   * @generated from field: string volume_id = 2;
   */
  volumeId = ''

  /**
   * Write enables the write api endpoints.
   *
   * @generated from field: bool write = 3;
   */
  write = false

  /**
   * ServiceId is the service id to serve LookupRpcService requests.
   * Cannot be empty.
   *
   * @generated from field: string service_id = 4;
   */
  serviceId = ''

  /**
   * ServerIdRe is the regex of server IDs to accept for LookupRpcService.
   * If empty, will accept any.
   *
   * @generated from field: string server_id_re = 5;
   */
  serverIdRe = ''

  /**
   * ForceHashType forces writing the given hash type to the store.
   * If unset, accepts any hash type the underlying bucket accepts.
   *
   * @generated from field: hash.HashType force_hash_type = 6;
   */
  forceHashType = HashType.HashType_UNKNOWN

  constructor(data?: PartialMessage<Config>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'block.store.rpc.server.Config'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'bucket_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'volume_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'write', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: 'service_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 5,
      name: 'server_id_re',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
    {
      no: 6,
      name: 'force_hash_type',
      kind: 'enum',
      T: proto3.getEnumType(HashType),
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): Config {
    return new Config().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): Config {
    return new Config().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): Config {
    return new Config().fromJsonString(jsonString, options)
  }

  static equals(
    a: Config | PlainMessage<Config> | undefined,
    b: Config | PlainMessage<Config> | undefined,
  ): boolean {
    return proto3.util.equals(Config, a, b)
  }
}
