# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: github.com/s4wave/spacewave/net/hash/hash.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'github.com/s4wave/spacewave/net/hash/hash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/github.com/s4wave/spacewave/net/hash/hash.proto\x12\x04hash\"7\n\x04Hash\x12!\n\thash_type\x18\x01 \x01(\x0e\x32\x0e.hash.HashType\x12\x0c\n\x04hash\x18\x02 \x01(\x0c*]\n\x08HashType\x12\x14\n\x10HashType_UNKNOWN\x10\x00\x12\x13\n\x0fHashType_SHA256\x10\x01\x12\x11\n\rHashType_SHA1\x10\x02\x12\x13\n\x0fHashType_BLAKE3\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'github.com.s4wave.spacewave.net.hash.hash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHTYPE']._serialized_start=114
  _globals['_HASHTYPE']._serialized_end=207
  _globals['_HASH']._serialized_start=57
  _globals['_HASH']._serialized_end=112
# @@protoc_insertion_point(module_scope)
