// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.15.1-0.20260724082201-6c49f1fd432b
// source: github.com/s4wave/spacewave/core/cdn/cdn.proto

package cdn

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	packfile "github.com/s4wave/spacewave/core/provider/spacewave/packfile"
	sobject "github.com/s4wave/spacewave/core/sobject"
)

// CdnRootPointer is the top-level CDN artifact for a public_read Space.
// The Worker writes it at cdn.spacewave.app/{spaceId}/root.packedmsg as a
// packedmsg-encoded blob (see repos/bldr/util/packedmsg) on every successful
// sync/push for a public_read Space. Anonymous clients fetch and decode this
// blob to discover the current signed root and the set of packs they need to
// reconstruct Space state; no Worker round-trip is required on the read path.
type CdnRootPointer struct {
	unknownFields []byte
	// SpaceId is the SharedObject ULID for this Space.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"spaceId,omitempty"`
	// Root is the signed SORoot for the Space at the time of publication.
	// Clients verify it against the config chain's validator peers.
	Root *sobject.SORoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// ConfigChainHash is the hash of the current config chain head.
	ConfigChainHash []byte `protobuf:"bytes,3,opt,name=config_chain_hash,json=configChainHash,proto3" json:"configChainHash,omitempty"`
	// ConfigChainSeqno is the seqno of the current config chain head.
	ConfigChainSeqno uint64 `protobuf:"varint,4,opt,name=config_chain_seqno,json=configChainSeqno,proto3" json:"configChainSeqno,omitempty"`
	// Packs is the list of packfile entries currently published to the CDN for
	// this Space. Each pack lives at
	// cdn.spacewave.app/{spaceId}/packs/{shard}/{id}.kvf. Bloom filters are
	// included so clients can skip packs that don't contain blocks they need.
	Packs []*packfile.PackfileEntry `protobuf:"bytes,5,rep,name=packs,proto3" json:"packs,omitempty"`
	// CreatedAtMs is when this root pointer was regenerated, expressed as unix
	// epoch milliseconds. Informational only; does not affect verification.
	CreatedAtMs int64 `protobuf:"varint,6,opt,name=created_at_ms,json=createdAtMs,proto3" json:"createdAtMs,omitempty"`
}

func (x *CdnRootPointer) Reset() {
	*x = CdnRootPointer{}
}

func (*CdnRootPointer) ProtoMessage() {}

func (x *CdnRootPointer) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CdnRootPointer) GetRoot() *sobject.SORoot {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CdnRootPointer) GetConfigChainHash() []byte {
	if x != nil {
		return x.ConfigChainHash
	}
	return nil
}

func (x *CdnRootPointer) GetConfigChainSeqno() uint64 {
	if x != nil {
		return x.ConfigChainSeqno
	}
	return 0
}

func (x *CdnRootPointer) GetPacks() []*packfile.PackfileEntry {
	if x != nil {
		return x.Packs
	}
	return nil
}

func (x *CdnRootPointer) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (m *CdnRootPointer) CloneVT() *CdnRootPointer {
	if m == nil {
		return (*CdnRootPointer)(nil)
	}
	r := new(CdnRootPointer)
	r.SpaceId = m.SpaceId
	r.ConfigChainSeqno = m.ConfigChainSeqno
	r.CreatedAtMs = m.CreatedAtMs
	r.Root = protobuf_go_lite.CloneVTValue(m.Root)
	r.ConfigChainHash = protobuf_go_lite.CloneBytes(m.ConfigChainHash)
	r.Packs = protobuf_go_lite.CloneVTSlice(m.Packs)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CdnRootPointer) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CdnRootPointer) EqualVT(that *CdnRootPointer) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.SpaceId != that.SpaceId {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Root, that.Root) {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.ConfigChainHash, that.ConfigChainHash) {
		return false
	}
	if this.ConfigChainSeqno != that.ConfigChainSeqno {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Packs, that.Packs, func() *packfile.PackfileEntry { return &packfile.PackfileEntry{} }) {
		return false
	}
	if this.CreatedAtMs != that.CreatedAtMs {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CdnRootPointer) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CdnRootPointer)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the CdnRootPointer message to JSON.
func (x *CdnRootPointer) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.SpaceId != "" || s.HasField("spaceId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("spaceId")
		s.WriteString(x.SpaceId)
	}
	if x.Root != nil || s.HasField("root") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("root")
		x.Root.MarshalProtoJSON(s.WithField("root"))
	}
	if len(x.ConfigChainHash) > 0 || s.HasField("configChainHash") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("configChainHash")
		s.WriteBytes(x.ConfigChainHash)
	}
	if x.ConfigChainSeqno != 0 || s.HasField("configChainSeqno") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("configChainSeqno")
		s.WriteUint64(x.ConfigChainSeqno)
	}
	if len(x.Packs) > 0 || s.HasField("packs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("packs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Packs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("packs"))
		}
		s.WriteArrayEnd()
	}
	if x.CreatedAtMs != 0 || s.HasField("createdAtMs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("createdAtMs")
		s.WriteInt64(x.CreatedAtMs)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CdnRootPointer to JSON.
func (x *CdnRootPointer) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CdnRootPointer message from JSON.
func (x *CdnRootPointer) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "space_id", "spaceId":
			s.AddField("space_id")
			x.SpaceId = s.ReadString()
		case "root":
			if s.ReadNil() {
				x.Root = nil
				return
			}
			x.Root = &sobject.SORoot{}
			x.Root.UnmarshalProtoJSON(s.WithField("root", true))
		case "config_chain_hash", "configChainHash":
			s.AddField("config_chain_hash")
			x.ConfigChainHash = s.ReadBytes()
		case "config_chain_seqno", "configChainSeqno":
			s.AddField("config_chain_seqno")
			x.ConfigChainSeqno = s.ReadUint64()
		case "packs":
			s.AddField("packs")
			if s.ReadNil() {
				x.Packs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Packs = append(x.Packs, nil)
					return
				}
				v := &packfile.PackfileEntry{}
				v.UnmarshalProtoJSON(s.WithField("packs", false))
				if s.Err() != nil {
					return
				}
				x.Packs = append(x.Packs, v)
			})
		case "created_at_ms", "createdAtMs":
			s.AddField("created_at_ms")
			x.CreatedAtMs = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the CdnRootPointer from JSON.
func (x *CdnRootPointer) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *CdnRootPointer) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CdnRootPointer) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CdnRootPointer) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.CreatedAtMs != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.CreatedAtMs))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Packs) > 0 {
		for iNdEx := len(m.Packs) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Packs[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ConfigChainSeqno != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ConfigChainSeqno))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ConfigChainHash) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.ConfigChainHash)
		i--
		dAtA[i] = 0x1a
	}
	if m.Root != nil {
		size, err := m.Root.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SpaceId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.SpaceId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CdnRootPointer) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.SpaceId)
	if m.Root != nil {
		l = m.Root.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.ConfigChainHash)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.ConfigChainSeqno)
	for _, e := range m.Packs {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeVarintNonZero(1, m.CreatedAtMs)
	n += len(m.unknownFields)
	return n
}

func (x *CdnRootPointer) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CdnRootPointer")
	if x.SpaceId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "space_id")
		protobuf_go_lite.TextWriteString(&sb, x.SpaceId)
	}
	if x.Root != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "root")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Root)
	}
	if len(x.ConfigChainHash) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "config_chain_hash")
		protobuf_go_lite.TextWriteBytes(&sb, x.ConfigChainHash)
	}
	if x.ConfigChainSeqno != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "config_chain_seqno")
		protobuf_go_lite.TextWriteUint(&sb, x.ConfigChainSeqno)
	}
	if len(x.Packs) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "packs")
		for i, v := range x.Packs {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &packfile.PackfileEntry{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.CreatedAtMs != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "created_at_ms")
		protobuf_go_lite.TextWriteInt(&sb, x.CreatedAtMs)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CdnRootPointer) String() string {
	return x.MarshalProtoText()
}

func (m *CdnRootPointer) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CdnRootPointer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CdnRootPointer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpaceId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SpaceId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Root == nil {
				m.Root = &sobject.SORoot{}
			}
			if err := m.Root.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigChainHash", wireType)
			}
			m.ConfigChainHash, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.ConfigChainHash, dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigChainSeqno", wireType)
			}
			m.ConfigChainSeqno = 0
			m.ConfigChainSeqno, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packs", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Packs = append(m.Packs, &packfile.PackfileEntry{})
			if err := m.Packs[len(m.Packs)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtMs", wireType)
			}
			m.CreatedAtMs = 0
			m.CreatedAtMs, iNdEx, err = protobuf_go_lite.DecodeVarintInt64(dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
