//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/s4wave/spacewave/core/bstore/world/world.proto
// Protobuf C++ Version: 6.33.4

#include "world.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bstore {
namespace world {

inline constexpr BlockStoreState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ref_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BlockStoreState::BlockStoreState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BlockStoreState_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BlockStoreStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockStoreStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockStoreStateDefaultTypeInternal() {}
  union {
    BlockStoreState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockStoreStateDefaultTypeInternal _BlockStoreState_default_instance_;

inline constexpr UpdateBlockStoreStateOp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        updated_state_{nullptr},
        if_not_exists_{false} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateBlockStoreStateOp::UpdateBlockStoreStateOp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UpdateBlockStoreStateOp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateBlockStoreStateOpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateBlockStoreStateOpDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateBlockStoreStateOpDefaultTypeInternal() {}
  union {
    UpdateBlockStoreStateOp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateBlockStoreStateOpDefaultTypeInternal _UpdateBlockStoreStateOp_default_instance_;
}  // namespace world
}  // namespace bstore
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bstore::world::BlockStoreState, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bstore::world::BlockStoreState, _impl_.ref_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bstore::world::UpdateBlockStoreStateOp, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bstore::world::UpdateBlockStoreStateOp, _impl_.updated_state_),
        PROTOBUF_FIELD_OFFSET(::bstore::world::UpdateBlockStoreStateOp, _impl_.if_not_exists_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::bstore::world::BlockStoreState)},
        {5, sizeof(::bstore::world::UpdateBlockStoreStateOp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::bstore::world::_BlockStoreState_default_instance_._instance,
    &::bstore::world::_UpdateBlockStoreStateOp_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n9github.com/s4wave/spacewave/core/bstor"
    "e/world/world.proto\022\014bstore.world\0324githu"
    "b.com/s4wave/spacewave/core/bstore/bstor"
    "e.proto\"5\n\017BlockStoreState\022\"\n\003ref\030\001 \001(\0132"
    "\025.bstore.BlockStoreRef\"f\n\027UpdateBlockSto"
    "reStateOp\0224\n\rupdated_state\030\001 \001(\0132\035.bstor"
    "e.world.BlockStoreState\022\025\n\rif_not_exists"
    "\030\002 \001(\010b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto_deps[1] = {
        &::descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fbstore_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto = {
    false,
    false,
    294,
    descriptor_table_protodef_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto,
    "github.com/s4wave/spacewave/core/bstore/world/world.proto",
    &descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto_once,
    descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto,
    file_level_service_descriptors_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto,
};
namespace bstore {
namespace world {
// ===================================================================

class BlockStoreState::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BlockStoreState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BlockStoreState, _impl_._has_bits_);
};

void BlockStoreState::clear_ref() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ref_ != nullptr) _impl_.ref_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
BlockStoreState::BlockStoreState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BlockStoreState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bstore.world.BlockStoreState)
}
PROTOBUF_NDEBUG_INLINE BlockStoreState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::bstore::world::BlockStoreState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

BlockStoreState::BlockStoreState(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BlockStoreState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BlockStoreState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BlockStoreState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ref_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ref_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:bstore.world.BlockStoreState)
}
PROTOBUF_NDEBUG_INLINE BlockStoreState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void BlockStoreState::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ref_ = {};
}
BlockStoreState::~BlockStoreState() {
  // @@protoc_insertion_point(destructor:bstore.world.BlockStoreState)
  SharedDtor(*this);
}
inline void BlockStoreState::SharedDtor(MessageLite& self) {
  BlockStoreState& this_ = static_cast<BlockStoreState&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.ref_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BlockStoreState::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BlockStoreState(arena);
}
constexpr auto BlockStoreState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BlockStoreState),
                                            alignof(BlockStoreState));
}
constexpr auto BlockStoreState::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BlockStoreState_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BlockStoreState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BlockStoreState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BlockStoreState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BlockStoreState>(), &BlockStoreState::ByteSizeLong,
              &BlockStoreState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BlockStoreState, _impl_._cached_size_),
          false,
      },
      &BlockStoreState::kDescriptorMethods,
      &descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BlockStoreState_class_data_ =
        BlockStoreState::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BlockStoreState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BlockStoreState_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BlockStoreState_class_data_.tc_table);
  return BlockStoreState_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
BlockStoreState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BlockStoreState, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BlockStoreState_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bstore::world::BlockStoreState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .bstore.BlockStoreRef ref = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BlockStoreState, _impl_.ref_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .bstore.BlockStoreRef ref = 1;
    {PROTOBUF_FIELD_OFFSET(BlockStoreState, _impl_.ref_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::bstore::BlockStoreRef>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BlockStoreState::Clear() {
// @@protoc_insertion_point(message_clear_start:bstore.world.BlockStoreState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.ref_ != nullptr);
    _impl_.ref_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BlockStoreState::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BlockStoreState& this_ = static_cast<const BlockStoreState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BlockStoreState::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BlockStoreState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bstore.world.BlockStoreState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .bstore.BlockStoreRef ref = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.ref_, this_._impl_.ref_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bstore.world.BlockStoreState)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BlockStoreState::ByteSizeLong(const MessageLite& base) {
  const BlockStoreState& this_ = static_cast<const BlockStoreState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BlockStoreState::ByteSizeLong() const {
  const BlockStoreState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bstore.world.BlockStoreState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .bstore.BlockStoreRef ref = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ref_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BlockStoreState::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BlockStoreState*>(&to_msg);
  auto& from = static_cast<const BlockStoreState&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bstore.world.BlockStoreState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(from._impl_.ref_ != nullptr);
    if (_this->_impl_.ref_ == nullptr) {
      _this->_impl_.ref_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ref_);
    } else {
      _this->_impl_.ref_->MergeFrom(*from._impl_.ref_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BlockStoreState::CopyFrom(const BlockStoreState& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bstore.world.BlockStoreState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BlockStoreState::InternalSwap(BlockStoreState* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.ref_, other->_impl_.ref_);
}

::google::protobuf::Metadata BlockStoreState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateBlockStoreStateOp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UpdateBlockStoreStateOp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_._has_bits_);
};

UpdateBlockStoreStateOp::UpdateBlockStoreStateOp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateBlockStoreStateOp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bstore.world.UpdateBlockStoreStateOp)
}
PROTOBUF_NDEBUG_INLINE UpdateBlockStoreStateOp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::bstore::world::UpdateBlockStoreStateOp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

UpdateBlockStoreStateOp::UpdateBlockStoreStateOp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UpdateBlockStoreStateOp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateBlockStoreStateOp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateBlockStoreStateOp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.updated_state_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.updated_state_)
                : nullptr;
  _impl_.if_not_exists_ = from._impl_.if_not_exists_;

  // @@protoc_insertion_point(copy_constructor:bstore.world.UpdateBlockStoreStateOp)
}
PROTOBUF_NDEBUG_INLINE UpdateBlockStoreStateOp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void UpdateBlockStoreStateOp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, updated_state_),
           0,
           offsetof(Impl_, if_not_exists_) -
               offsetof(Impl_, updated_state_) +
               sizeof(Impl_::if_not_exists_));
}
UpdateBlockStoreStateOp::~UpdateBlockStoreStateOp() {
  // @@protoc_insertion_point(destructor:bstore.world.UpdateBlockStoreStateOp)
  SharedDtor(*this);
}
inline void UpdateBlockStoreStateOp::SharedDtor(MessageLite& self) {
  UpdateBlockStoreStateOp& this_ = static_cast<UpdateBlockStoreStateOp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.updated_state_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UpdateBlockStoreStateOp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UpdateBlockStoreStateOp(arena);
}
constexpr auto UpdateBlockStoreStateOp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateBlockStoreStateOp),
                                            alignof(UpdateBlockStoreStateOp));
}
constexpr auto UpdateBlockStoreStateOp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UpdateBlockStoreStateOp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UpdateBlockStoreStateOp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UpdateBlockStoreStateOp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UpdateBlockStoreStateOp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UpdateBlockStoreStateOp>(), &UpdateBlockStoreStateOp::ByteSizeLong,
              &UpdateBlockStoreStateOp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_._cached_size_),
          false,
      },
      &UpdateBlockStoreStateOp::kDescriptorMethods,
      &descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UpdateBlockStoreStateOp_class_data_ =
        UpdateBlockStoreStateOp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UpdateBlockStoreStateOp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UpdateBlockStoreStateOp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UpdateBlockStoreStateOp_class_data_.tc_table);
  return UpdateBlockStoreStateOp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
UpdateBlockStoreStateOp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    UpdateBlockStoreStateOp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bstore::world::UpdateBlockStoreStateOp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool if_not_exists = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateBlockStoreStateOp, _impl_.if_not_exists_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.if_not_exists_)}},
    // .bstore.world.BlockStoreState updated_state = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.updated_state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .bstore.world.BlockStoreState updated_state = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.updated_state_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool if_not_exists = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.if_not_exists_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::bstore::world::BlockStoreState>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void UpdateBlockStoreStateOp::Clear() {
// @@protoc_insertion_point(message_clear_start:bstore.world.UpdateBlockStoreStateOp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.updated_state_ != nullptr);
    _impl_.updated_state_->Clear();
  }
  _impl_.if_not_exists_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UpdateBlockStoreStateOp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UpdateBlockStoreStateOp& this_ = static_cast<const UpdateBlockStoreStateOp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UpdateBlockStoreStateOp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UpdateBlockStoreStateOp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bstore.world.UpdateBlockStoreStateOp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .bstore.world.BlockStoreState updated_state = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.updated_state_, this_._impl_.updated_state_->GetCachedSize(), target,
        stream);
  }

  // bool if_not_exists = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_if_not_exists() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_if_not_exists(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bstore.world.UpdateBlockStoreStateOp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UpdateBlockStoreStateOp::ByteSizeLong(const MessageLite& base) {
  const UpdateBlockStoreStateOp& this_ = static_cast<const UpdateBlockStoreStateOp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UpdateBlockStoreStateOp::ByteSizeLong() const {
  const UpdateBlockStoreStateOp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bstore.world.UpdateBlockStoreStateOp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .bstore.world.BlockStoreState updated_state = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.updated_state_);
    }
    // bool if_not_exists = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_if_not_exists() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UpdateBlockStoreStateOp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<UpdateBlockStoreStateOp*>(&to_msg);
  auto& from = static_cast<const UpdateBlockStoreStateOp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bstore.world.UpdateBlockStoreStateOp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.updated_state_ != nullptr);
      if (_this->_impl_.updated_state_ == nullptr) {
        _this->_impl_.updated_state_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.updated_state_);
      } else {
        _this->_impl_.updated_state_->MergeFrom(*from._impl_.updated_state_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_if_not_exists() != 0) {
        _this->_impl_.if_not_exists_ = from._impl_.if_not_exists_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UpdateBlockStoreStateOp::CopyFrom(const UpdateBlockStoreStateOp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bstore.world.UpdateBlockStoreStateOp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateBlockStoreStateOp::InternalSwap(UpdateBlockStoreStateOp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.if_not_exists_)
      + sizeof(UpdateBlockStoreStateOp::_impl_.if_not_exists_)
      - PROTOBUF_FIELD_OFFSET(UpdateBlockStoreStateOp, _impl_.updated_state_)>(
          reinterpret_cast<char*>(&_impl_.updated_state_),
          reinterpret_cast<char*>(&other->_impl_.updated_state_));
}

::google::protobuf::Metadata UpdateBlockStoreStateOp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace world
}  // namespace bstore
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2fs4wave_2fspacewave_2fcore_2fbstore_2fworld_2fworld_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
