// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/hydra/unixfs/world/unixfs.proto

package unixfs_world

import (
	fmt "fmt"
	math "math"

	block1 "github.com/aperturerobotics/hydra/block"
	bucket "github.com/aperturerobotics/hydra/bucket"
	block "github.com/aperturerobotics/hydra/unixfs/block"
	timestamp "github.com/aperturerobotics/timestamp"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FSType indicates the type of unixfs reference.
type FSType int32

const (
	// FSType_UNKNOWN is the zero type.
	// Defaults depending on the context.
	FSType_FSType_UNKNOWN FSType = 0
	// FSType_FS_NODE is a raw fstree FSNode block (without changelog).
	FSType_FSType_FS_NODE FSType = 1
	// FSType_FS_OBJECT is a FSObject tree (with changelog).
	FSType_FSType_FS_OBJECT FSType = 2
	// FSType_FS_HOST_VOLUME is a FSHostVolume object.
	FSType_FSType_FS_HOST_VOLUME FSType = 3
)

var FSType_name = map[int32]string{
	0: "FSType_UNKNOWN",
	1: "FSType_FS_NODE",
	2: "FSType_FS_OBJECT",
	3: "FSType_FS_HOST_VOLUME",
}

var FSType_value = map[string]int32{
	"FSType_UNKNOWN":        0,
	"FSType_FS_NODE":        1,
	"FSType_FS_OBJECT":      2,
	"FSType_FS_HOST_VOLUME": 3,
}

func (x FSType) String() string {
	return proto.EnumName(FSType_name, int32(x))
}

func (FSType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{0}
}

// UnixfsRef is a reference to a UnixFS object in a World.
type UnixfsRef struct {
	// ObjectKey is the object key to open as a UnixFS.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType sets the expected filesystem object type at object_key.
	// If unset (0) reads the type from the graph.
	// Defaults to FS_NODE if nothing else set.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Path is the location within the FS.
	// If empty, defaults to / (the root).
	Path                 *block.FSPath `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnixfsRef) Reset()         { *m = UnixfsRef{} }
func (m *UnixfsRef) String() string { return proto.CompactTextString(m) }
func (*UnixfsRef) ProtoMessage()    {}
func (*UnixfsRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{0}
}

func (m *UnixfsRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnixfsRef.Unmarshal(m, b)
}
func (m *UnixfsRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnixfsRef.Marshal(b, m, deterministic)
}
func (m *UnixfsRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnixfsRef.Merge(m, src)
}
func (m *UnixfsRef) XXX_Size() int {
	return xxx_messageInfo_UnixfsRef.Size(m)
}
func (m *UnixfsRef) XXX_DiscardUnknown() {
	xxx_messageInfo_UnixfsRef.DiscardUnknown(m)
}

var xxx_messageInfo_UnixfsRef proto.InternalMessageInfo

func (m *UnixfsRef) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *UnixfsRef) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *UnixfsRef) GetPath() *block.FSPath {
	if m != nil {
		return m.Path
	}
	return nil
}

// FsInitOp is an operation to create a unixfs filesystem with a root ref or empty.
// Can be applied as either an object op or a world op.
type FsInitOp struct {
	// ObjectKey is the object key to create as a UnixFS.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType sets the filesystem object type to create.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// FsRef contains a initial object ref to use the root of the UnixFS.
	// If empty, will create a new blank fs.
	FsRef *bucket.ObjectRef `protobuf:"bytes,3,opt,name=fs_ref,json=fsRef,proto3" json:"fs_ref,omitempty"`
	// FsRefType is the FSType of the ref.
	// Defaults to FsType_FS_NODE.
	FsRefType FSType `protobuf:"varint,4,opt,name=fs_ref_type,json=fsRefType,proto3,enum=unixfs.world.FSType" json:"fs_ref_type,omitempty"`
	// FsOverwrite indicates to overwrite any existing object.
	FsOverwrite bool `protobuf:"varint,5,opt,name=fs_overwrite,json=fsOverwrite,proto3" json:"fs_overwrite,omitempty"`
	// Timestamp is the modification time for the fs root.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsInitOp) Reset()         { *m = FsInitOp{} }
func (m *FsInitOp) String() string { return proto.CompactTextString(m) }
func (*FsInitOp) ProtoMessage()    {}
func (*FsInitOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{1}
}

func (m *FsInitOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsInitOp.Unmarshal(m, b)
}
func (m *FsInitOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsInitOp.Marshal(b, m, deterministic)
}
func (m *FsInitOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsInitOp.Merge(m, src)
}
func (m *FsInitOp) XXX_Size() int {
	return xxx_messageInfo_FsInitOp.Size(m)
}
func (m *FsInitOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsInitOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsInitOp proto.InternalMessageInfo

func (m *FsInitOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsInitOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsInitOp) GetFsRef() *bucket.ObjectRef {
	if m != nil {
		return m.FsRef
	}
	return nil
}

func (m *FsInitOp) GetFsRefType() FSType {
	if m != nil {
		return m.FsRefType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsInitOp) GetFsOverwrite() bool {
	if m != nil {
		return m.FsOverwrite
	}
	return false
}

func (m *FsInitOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsMknodOp is an operation to create one or more inodes at paths.
// Can be applied as either an object op or a world op.
type FsMknodOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Paths are the paths to the new inodes.
	Paths []*block.FSPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Permissions is the permissions bitset.
	// If zero uses defaults.
	Permissions uint32 `protobuf:"varint,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// NodeType is the node type to create.
	NodeType block.NodeType `protobuf:"varint,5,opt,name=node_type,json=nodeType,proto3,enum=unixfs.block.NodeType" json:"node_type,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsMknodOp) Reset()         { *m = FsMknodOp{} }
func (m *FsMknodOp) String() string { return proto.CompactTextString(m) }
func (*FsMknodOp) ProtoMessage()    {}
func (*FsMknodOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{2}
}

func (m *FsMknodOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsMknodOp.Unmarshal(m, b)
}
func (m *FsMknodOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsMknodOp.Marshal(b, m, deterministic)
}
func (m *FsMknodOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsMknodOp.Merge(m, src)
}
func (m *FsMknodOp) XXX_Size() int {
	return xxx_messageInfo_FsMknodOp.Size(m)
}
func (m *FsMknodOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsMknodOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsMknodOp proto.InternalMessageInfo

func (m *FsMknodOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsMknodOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsMknodOp) GetPaths() []*block.FSPath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *FsMknodOp) GetPermissions() uint32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *FsMknodOp) GetNodeType() block.NodeType {
	if m != nil {
		return m.NodeType
	}
	return block.NodeType_NodeType_UNKNOWN
}

func (m *FsMknodOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsSymlinkOp is an operation to create a symbolic link.
// Can be applied as either an object op or a world op.
type FsSymlinkOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Path is the paths to the symbolic link source.
	Path *block.FSPath `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Symlink is the contents of the symlink.
	Symlink *block.FSSymlink `protobuf:"bytes,4,opt,name=symlink,proto3" json:"symlink,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsSymlinkOp) Reset()         { *m = FsSymlinkOp{} }
func (m *FsSymlinkOp) String() string { return proto.CompactTextString(m) }
func (*FsSymlinkOp) ProtoMessage()    {}
func (*FsSymlinkOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{3}
}

func (m *FsSymlinkOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsSymlinkOp.Unmarshal(m, b)
}
func (m *FsSymlinkOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsSymlinkOp.Marshal(b, m, deterministic)
}
func (m *FsSymlinkOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsSymlinkOp.Merge(m, src)
}
func (m *FsSymlinkOp) XXX_Size() int {
	return xxx_messageInfo_FsSymlinkOp.Size(m)
}
func (m *FsSymlinkOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsSymlinkOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsSymlinkOp proto.InternalMessageInfo

func (m *FsSymlinkOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsSymlinkOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsSymlinkOp) GetPath() *block.FSPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FsSymlinkOp) GetSymlink() *block.FSSymlink {
	if m != nil {
		return m.Symlink
	}
	return nil
}

func (m *FsSymlinkOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsSetPermissionsOp is an operation to set the permissions at the paths.
// The file mode portion of the permissions bitset will be ignored.
// Can be applied as either an object op or a world op.
type FsSetPermissionsOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Paths are the paths to update permissions for.
	Paths []*block.FSPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Permissions is the permissions bitset.
	Permissions uint32 `protobuf:"varint,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsSetPermissionsOp) Reset()         { *m = FsSetPermissionsOp{} }
func (m *FsSetPermissionsOp) String() string { return proto.CompactTextString(m) }
func (*FsSetPermissionsOp) ProtoMessage()    {}
func (*FsSetPermissionsOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{4}
}

func (m *FsSetPermissionsOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsSetPermissionsOp.Unmarshal(m, b)
}
func (m *FsSetPermissionsOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsSetPermissionsOp.Marshal(b, m, deterministic)
}
func (m *FsSetPermissionsOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsSetPermissionsOp.Merge(m, src)
}
func (m *FsSetPermissionsOp) XXX_Size() int {
	return xxx_messageInfo_FsSetPermissionsOp.Size(m)
}
func (m *FsSetPermissionsOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsSetPermissionsOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsSetPermissionsOp proto.InternalMessageInfo

func (m *FsSetPermissionsOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsSetPermissionsOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsSetPermissionsOp) GetPaths() []*block.FSPath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *FsSetPermissionsOp) GetPermissions() uint32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *FsSetPermissionsOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsSetModTimestampOp is an operation to set the modification timestamp at the paths.
// Can be applied as either an object op or a world op.
type FsSetModTimestampOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Paths are the paths to update the timestamp for.
	Paths []*block.FSPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsSetModTimestampOp) Reset()         { *m = FsSetModTimestampOp{} }
func (m *FsSetModTimestampOp) String() string { return proto.CompactTextString(m) }
func (*FsSetModTimestampOp) ProtoMessage()    {}
func (*FsSetModTimestampOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{5}
}

func (m *FsSetModTimestampOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsSetModTimestampOp.Unmarshal(m, b)
}
func (m *FsSetModTimestampOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsSetModTimestampOp.Marshal(b, m, deterministic)
}
func (m *FsSetModTimestampOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsSetModTimestampOp.Merge(m, src)
}
func (m *FsSetModTimestampOp) XXX_Size() int {
	return xxx_messageInfo_FsSetModTimestampOp.Size(m)
}
func (m *FsSetModTimestampOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsSetModTimestampOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsSetModTimestampOp proto.InternalMessageInfo

func (m *FsSetModTimestampOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsSetModTimestampOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsSetModTimestampOp) GetPaths() []*block.FSPath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *FsSetModTimestampOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsWriteOp is an operation to write some data to a file.
// Can be applied as either an object op or a world op.
type FsWriteOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Path is the path to write to.
	Path *block.FSPath `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Offset is the location to write the data to.
	Offset int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// BlobRef is the reference to the Blob to write.
	BlobRef *block1.BlockRef `protobuf:"bytes,5,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsWriteOp) Reset()         { *m = FsWriteOp{} }
func (m *FsWriteOp) String() string { return proto.CompactTextString(m) }
func (*FsWriteOp) ProtoMessage()    {}
func (*FsWriteOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{6}
}

func (m *FsWriteOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsWriteOp.Unmarshal(m, b)
}
func (m *FsWriteOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsWriteOp.Marshal(b, m, deterministic)
}
func (m *FsWriteOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsWriteOp.Merge(m, src)
}
func (m *FsWriteOp) XXX_Size() int {
	return xxx_messageInfo_FsWriteOp.Size(m)
}
func (m *FsWriteOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsWriteOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsWriteOp proto.InternalMessageInfo

func (m *FsWriteOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsWriteOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsWriteOp) GetPath() *block.FSPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FsWriteOp) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FsWriteOp) GetBlobRef() *block1.BlockRef {
	if m != nil {
		return m.BlobRef
	}
	return nil
}

func (m *FsWriteOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsTruncateOp shrinks or extends a file to the specified size.
// The extended part will be a sparse range (hole) reading as zeros.
// Can be applied as either an object op or a world op.
type FsTruncateOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Path is the path to write to.
	Path *block.FSPath `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// FileSize is the new size to truncate to.
	FileSize int64 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsTruncateOp) Reset()         { *m = FsTruncateOp{} }
func (m *FsTruncateOp) String() string { return proto.CompactTextString(m) }
func (*FsTruncateOp) ProtoMessage()    {}
func (*FsTruncateOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{7}
}

func (m *FsTruncateOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsTruncateOp.Unmarshal(m, b)
}
func (m *FsTruncateOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsTruncateOp.Marshal(b, m, deterministic)
}
func (m *FsTruncateOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsTruncateOp.Merge(m, src)
}
func (m *FsTruncateOp) XXX_Size() int {
	return xxx_messageInfo_FsTruncateOp.Size(m)
}
func (m *FsTruncateOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsTruncateOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsTruncateOp proto.InternalMessageInfo

func (m *FsTruncateOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsTruncateOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsTruncateOp) GetPath() *block.FSPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FsTruncateOp) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FsTruncateOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsCopyOp recursively copies a source path to a destination, overwriting destination.
// Note: this does not allow cross-FS copy.
// Can be applied as either an object op or a world op.
type FsCopyOp struct {
	// ObjectKey is the object key to copy from.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// SrcPath is the path to copy from.
	SrcPath *block.FSPath `protobuf:"bytes,3,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	// DestPath is the path to copy to.
	DestPath *block.FSPath `protobuf:"bytes,4,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsCopyOp) Reset()         { *m = FsCopyOp{} }
func (m *FsCopyOp) String() string { return proto.CompactTextString(m) }
func (*FsCopyOp) ProtoMessage()    {}
func (*FsCopyOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{8}
}

func (m *FsCopyOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsCopyOp.Unmarshal(m, b)
}
func (m *FsCopyOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsCopyOp.Marshal(b, m, deterministic)
}
func (m *FsCopyOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsCopyOp.Merge(m, src)
}
func (m *FsCopyOp) XXX_Size() int {
	return xxx_messageInfo_FsCopyOp.Size(m)
}
func (m *FsCopyOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsCopyOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsCopyOp proto.InternalMessageInfo

func (m *FsCopyOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsCopyOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsCopyOp) GetSrcPath() *block.FSPath {
	if m != nil {
		return m.SrcPath
	}
	return nil
}

func (m *FsCopyOp) GetDestPath() *block.FSPath {
	if m != nil {
		return m.DestPath
	}
	return nil
}

func (m *FsCopyOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsRenameOp recursively moves a source path to a destination, overwriting destination.
// This applies a FsCopyOp followed by a Remove in the same operation.
// Note: this does not allow cross-FS rename.
// Can be applied as either an object op or a world op.
type FsRenameOp struct {
	// ObjectKey is the object key to copy from.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// SrcPath is the path to move from.
	SrcPath *block.FSPath `protobuf:"bytes,3,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	// DestPath is the path to move to.
	DestPath *block.FSPath `protobuf:"bytes,4,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsRenameOp) Reset()         { *m = FsRenameOp{} }
func (m *FsRenameOp) String() string { return proto.CompactTextString(m) }
func (*FsRenameOp) ProtoMessage()    {}
func (*FsRenameOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{9}
}

func (m *FsRenameOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsRenameOp.Unmarshal(m, b)
}
func (m *FsRenameOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsRenameOp.Marshal(b, m, deterministic)
}
func (m *FsRenameOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsRenameOp.Merge(m, src)
}
func (m *FsRenameOp) XXX_Size() int {
	return xxx_messageInfo_FsRenameOp.Size(m)
}
func (m *FsRenameOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsRenameOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsRenameOp proto.InternalMessageInfo

func (m *FsRenameOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsRenameOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsRenameOp) GetSrcPath() *block.FSPath {
	if m != nil {
		return m.SrcPath
	}
	return nil
}

func (m *FsRenameOp) GetDestPath() *block.FSPath {
	if m != nil {
		return m.DestPath
	}
	return nil
}

func (m *FsRenameOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// FsRemoveOp is an operation to delete inodes from the tree.
// Can be applied as either an object op or a world op.
type FsRemoveOp struct {
	// ObjectKey is the object key to start at.
	// Ignored if applied as an object op.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// FsType is the type of object located at ObjectKey.
	// Defaults to FsType_FS_NODE.
	FsType FSType `protobuf:"varint,2,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Paths are the paths to delete.
	Paths []*block.FSPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Timestamp is the modification time.
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FsRemoveOp) Reset()         { *m = FsRemoveOp{} }
func (m *FsRemoveOp) String() string { return proto.CompactTextString(m) }
func (*FsRemoveOp) ProtoMessage()    {}
func (*FsRemoveOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{10}
}

func (m *FsRemoveOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FsRemoveOp.Unmarshal(m, b)
}
func (m *FsRemoveOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FsRemoveOp.Marshal(b, m, deterministic)
}
func (m *FsRemoveOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FsRemoveOp.Merge(m, src)
}
func (m *FsRemoveOp) XXX_Size() int {
	return xxx_messageInfo_FsRemoveOp.Size(m)
}
func (m *FsRemoveOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FsRemoveOp.DiscardUnknown(m)
}

var xxx_messageInfo_FsRemoveOp proto.InternalMessageInfo

func (m *FsRemoveOp) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *FsRemoveOp) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *FsRemoveOp) GetPaths() []*block.FSPath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *FsRemoveOp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// MountValue is the contents of the quad value field for a mount.
// inode -> unixfs/mount -> inode <value=mount-value>
type MountValue struct {
	// Mountpoint is the path inside the inode to mount at.
	// If empty assumes /
	Mountpoint string `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	// Prefix is the path inside the target inode to link to.
	// If empty assumes /
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountValue) Reset()         { *m = MountValue{} }
func (m *MountValue) String() string { return proto.CompactTextString(m) }
func (*MountValue) ProtoMessage()    {}
func (*MountValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{11}
}

func (m *MountValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountValue.Unmarshal(m, b)
}
func (m *MountValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountValue.Marshal(b, m, deterministic)
}
func (m *MountValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountValue.Merge(m, src)
}
func (m *MountValue) XXX_Size() int {
	return xxx_messageInfo_MountValue.Size(m)
}
func (m *MountValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MountValue.DiscardUnknown(m)
}

var xxx_messageInfo_MountValue proto.InternalMessageInfo

func (m *MountValue) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

func (m *MountValue) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// RefValue is the contents of the quad value field for a ref.
// i.e.: somewhere git/workdir -> inode <ref-value>
type RefValue struct {
	// FsType sets the expected filesystem object type at the target.
	// If unset (0) reads the type from the graph.
	// Defaults to FS_NODE if nothing else set.
	FsType FSType `protobuf:"varint,1,opt,name=fs_type,json=fsType,proto3,enum=unixfs.world.FSType" json:"fs_type,omitempty"`
	// Path is the location within the FS.
	// If empty, defaults to / (the root).
	Path                 *block.FSPath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RefValue) Reset()         { *m = RefValue{} }
func (m *RefValue) String() string { return proto.CompactTextString(m) }
func (*RefValue) ProtoMessage()    {}
func (*RefValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_128fb99f20464bc3, []int{12}
}

func (m *RefValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefValue.Unmarshal(m, b)
}
func (m *RefValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefValue.Marshal(b, m, deterministic)
}
func (m *RefValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefValue.Merge(m, src)
}
func (m *RefValue) XXX_Size() int {
	return xxx_messageInfo_RefValue.Size(m)
}
func (m *RefValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RefValue.DiscardUnknown(m)
}

var xxx_messageInfo_RefValue proto.InternalMessageInfo

func (m *RefValue) GetFsType() FSType {
	if m != nil {
		return m.FsType
	}
	return FSType_FSType_UNKNOWN
}

func (m *RefValue) GetPath() *block.FSPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func init() {
	proto.RegisterEnum("unixfs.world.FSType", FSType_name, FSType_value)
	proto.RegisterType((*UnixfsRef)(nil), "unixfs.world.UnixfsRef")
	proto.RegisterType((*FsInitOp)(nil), "unixfs.world.FsInitOp")
	proto.RegisterType((*FsMknodOp)(nil), "unixfs.world.FsMknodOp")
	proto.RegisterType((*FsSymlinkOp)(nil), "unixfs.world.FsSymlinkOp")
	proto.RegisterType((*FsSetPermissionsOp)(nil), "unixfs.world.FsSetPermissionsOp")
	proto.RegisterType((*FsSetModTimestampOp)(nil), "unixfs.world.FsSetModTimestampOp")
	proto.RegisterType((*FsWriteOp)(nil), "unixfs.world.FsWriteOp")
	proto.RegisterType((*FsTruncateOp)(nil), "unixfs.world.FsTruncateOp")
	proto.RegisterType((*FsCopyOp)(nil), "unixfs.world.FsCopyOp")
	proto.RegisterType((*FsRenameOp)(nil), "unixfs.world.FsRenameOp")
	proto.RegisterType((*FsRemoveOp)(nil), "unixfs.world.FsRemoveOp")
	proto.RegisterType((*MountValue)(nil), "unixfs.world.MountValue")
	proto.RegisterType((*RefValue)(nil), "unixfs.world.RefValue")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/hydra/unixfs/world/unixfs.proto", fileDescriptor_128fb99f20464bc3)
}

var fileDescriptor_128fb99f20464bc3 = []byte{
	// 751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xcd, 0x72, 0xd3, 0x48,
	0x10, 0x5e, 0xf9, 0x57, 0x6a, 0x67, 0xb3, 0x5e, 0x6d, 0x36, 0xeb, 0xcd, 0xd6, 0x6e, 0x79, 0x7d,
	0x72, 0xa5, 0x0a, 0xbb, 0x48, 0xe0, 0xc4, 0x2d, 0x3f, 0x2a, 0x20, 0xd8, 0x4a, 0xc9, 0x4e, 0x72,
	0x54, 0xc9, 0x72, 0x0b, 0x0b, 0x5b, 0x1a, 0xd5, 0xcc, 0x38, 0x89, 0x73, 0xe5, 0x01, 0xe0, 0x79,
	0xb8, 0xf2, 0x10, 0xbc, 0x00, 0x47, 0x0e, 0x14, 0x57, 0x2e, 0x94, 0x66, 0x26, 0xb1, 0x43, 0x15,
	0x89, 0x71, 0x85, 0x0a, 0x14, 0x17, 0x69, 0xa6, 0xfd, 0x75, 0x4f, 0x7f, 0xdf, 0x74, 0xb7, 0x05,
	0x0f, 0x9e, 0x86, 0x7c, 0x30, 0xee, 0x35, 0x7c, 0x12, 0x35, 0xbd, 0x04, 0x29, 0x1f, 0x53, 0xa4,
	0xa4, 0x47, 0x78, 0xe8, 0xb3, 0xe6, 0x60, 0xd2, 0xa7, 0x5e, 0x73, 0x1c, 0x87, 0xa7, 0x01, 0x6b,
	0x9e, 0x10, 0x3a, 0xea, 0xab, 0x4d, 0x23, 0xa1, 0x84, 0x13, 0x73, 0x49, 0xed, 0xc4, 0x4f, 0x6b,
	0x9b, 0xd7, 0x87, 0xea, 0x8d, 0x88, 0x3f, 0x94, 0x4f, 0x19, 0x62, 0xed, 0xfe, 0x1c, 0x4e, 0x63,
	0x7f, 0x88, 0x5c, 0xbd, 0x94, 0xdb, 0xfc, 0x69, 0xcb, 0x23, 0x03, 0xc6, 0x29, 0xe2, 0x3c, 0x67,
	0xf2, 0x30, 0x42, 0xc6, 0xbd, 0x28, 0x99, 0xae, 0xa4, 0x5b, 0xed, 0xb9, 0x06, 0xc6, 0x81, 0x08,
	0xea, 0x60, 0x60, 0xfe, 0x0b, 0x40, 0x7a, 0xcf, 0xd0, 0xe7, 0xee, 0x10, 0x27, 0x15, 0xad, 0xaa,
	0xd5, 0x0d, 0xc7, 0x90, 0x96, 0x3d, 0x9c, 0x98, 0x77, 0xa0, 0x18, 0x30, 0x97, 0x4f, 0x12, 0xac,
	0x64, 0xaa, 0x5a, 0x7d, 0x79, 0x63, 0xa5, 0x31, 0x2b, 0x56, 0xc3, 0xea, 0x74, 0x27, 0x09, 0x3a,
	0x85, 0x80, 0xa5, 0x6f, 0xb3, 0x0e, 0xb9, 0xc4, 0xe3, 0x83, 0x4a, 0xb6, 0xaa, 0xd5, 0x4b, 0x53,
	0xac, 0x54, 0xca, 0xea, 0xec, 0x7b, 0x7c, 0xe0, 0x08, 0x44, 0xed, 0x45, 0x06, 0x74, 0x8b, 0x3d,
	0x8a, 0x43, 0x6e, 0x27, 0x37, 0x9e, 0x44, 0x21, 0x60, 0x2e, 0xc5, 0x40, 0xa5, 0xf1, 0x7b, 0x43,
	0x69, 0x6e, 0x8b, 0x88, 0x0e, 0x06, 0x4e, 0x5e, 0x92, 0xbf, 0x07, 0x25, 0x89, 0x94, 0xc1, 0x73,
	0x57, 0x04, 0x37, 0x84, 0x87, 0x88, 0xff, 0x3f, 0x2c, 0x05, 0xcc, 0x25, 0xc7, 0x48, 0x4f, 0x68,
	0xc8, 0xb1, 0x92, 0xaf, 0x6a, 0x75, 0xdd, 0x29, 0x05, 0xcc, 0x3e, 0x37, 0x99, 0x1b, 0x60, 0x5c,
	0xc8, 0x5e, 0x29, 0x28, 0x31, 0xa6, 0x17, 0xd1, 0x3d, 0x5f, 0x39, 0x53, 0x58, 0xed, 0x65, 0x06,
	0x0c, 0x8b, 0xb5, 0x86, 0x31, 0xe9, 0xdf, 0xb8, 0x24, 0xeb, 0x90, 0x4f, 0x55, 0x67, 0x95, 0x6c,
	0x35, 0xfb, 0xc5, 0x8b, 0x91, 0x10, 0xb3, 0x0a, 0xa5, 0x04, 0x69, 0x14, 0x32, 0x16, 0x92, 0x98,
	0x09, 0x51, 0x7e, 0x75, 0x66, 0x4d, 0xe6, 0x26, 0x18, 0x31, 0xe9, 0xa3, 0x3c, 0x3e, 0x2f, 0x8e,
	0x5f, 0xbd, 0x1c, 0xb1, 0x4d, 0xfa, 0x28, 0x12, 0xd0, 0x63, 0xb5, 0x5a, 0x48, 0x92, 0x77, 0x1a,
	0x94, 0x2c, 0xd6, 0x99, 0x44, 0xa3, 0x30, 0x1e, 0x7e, 0x83, 0x3a, 0x99, 0xb3, 0x58, 0xcd, 0xbb,
	0x50, 0x64, 0x32, 0x09, 0x21, 0x47, 0x69, 0xe3, 0xaf, 0xcf, 0xc1, 0x2a, 0x47, 0xe7, 0x1c, 0x77,
	0x99, 0x6e, 0x7e, 0x3e, 0xba, 0x6f, 0x35, 0x30, 0x2d, 0xd6, 0x41, 0xbe, 0x3f, 0x15, 0xfb, 0x3b,
	0x2f, 0x85, 0x45, 0x68, 0xbe, 0xd6, 0xe0, 0x0f, 0x41, 0xb3, 0x45, 0xfa, 0x17, 0x80, 0x5b, 0xe5,
	0x79, 0x89, 0x45, 0x6e, 0x3e, 0x16, 0x1f, 0xb5, 0xb4, 0x5d, 0x8f, 0xd2, 0x76, 0xbf, 0xc5, 0xca,
	0x5c, 0x85, 0x02, 0x09, 0x02, 0x86, 0x5c, 0xa4, 0x9d, 0x75, 0xd4, 0xce, 0x5c, 0x07, 0xbd, 0x37,
	0x22, 0x3d, 0x31, 0x05, 0xe5, 0xb5, 0xfc, 0xa6, 0xdc, 0xb7, 0xd2, 0x67, 0x3a, 0x03, 0x8b, 0x29,
	0x20, 0x9d, 0x82, 0x8b, 0x74, 0xe6, 0x1b, 0x0d, 0x96, 0x2c, 0xd6, 0xa5, 0xe3, 0xd8, 0xf7, 0x6e,
	0x55, 0x80, 0x7f, 0xc0, 0x08, 0xc2, 0x11, 0xba, 0x2c, 0x3c, 0x43, 0xa5, 0x81, 0x9e, 0x1a, 0x3a,
	0xe1, 0x19, 0x2e, 0x54, 0x9d, 0xef, 0xb5, 0xf4, 0x8f, 0x69, 0x9b, 0x24, 0x93, 0x1b, 0x67, 0xd5,
	0x04, 0x9d, 0x51, 0xdf, 0xbd, 0x96, 0x59, 0x91, 0x51, 0x7f, 0x5f, 0xce, 0x1d, 0xa3, 0x8f, 0x8c,
	0x4b, 0x8f, 0xdc, 0x15, 0x1e, 0x7a, 0x0a, 0x13, 0x2e, 0x8b, 0x50, 0xfe, 0xa0, 0x01, 0x58, 0xcc,
	0xc1, 0xd8, 0x8b, 0xf0, 0xa7, 0x21, 0xfd, 0x4a, 0x91, 0x8e, 0xc8, 0x31, 0xfe, 0x70, 0xc3, 0x67,
	0x07, 0xa0, 0x45, 0xc6, 0x31, 0x3f, 0xf4, 0x46, 0x63, 0x34, 0xff, 0x03, 0x88, 0xd2, 0x5d, 0x42,
	0xc2, 0x98, 0xab, 0xdc, 0x67, 0x2c, 0xe9, 0x90, 0x48, 0x28, 0x06, 0xe1, 0xa9, 0xc8, 0xdd, 0x70,
	0xd4, 0xae, 0xe6, 0x83, 0xee, 0x60, 0x20, 0x63, 0xcc, 0x10, 0xd4, 0xbe, 0xa2, 0x41, 0x33, 0xd7,
	0x35, 0xe8, 0xba, 0x07, 0x05, 0xe9, 0x6b, 0x9a, 0xb0, 0x2c, 0x57, 0xee, 0x41, 0x7b, 0xaf, 0x6d,
	0x1f, 0xb5, 0xcb, 0xbf, 0xcc, 0xd8, 0xac, 0x8e, 0xdb, 0xb6, 0x77, 0x76, 0xcb, 0x9a, 0xb9, 0x02,
	0xe5, 0xa9, 0xcd, 0xde, 0x7a, 0xbc, 0xbb, 0xdd, 0x2d, 0x67, 0xcc, 0xbf, 0xe1, 0xcf, 0xa9, 0xf5,
	0xa1, 0xdd, 0xe9, 0xba, 0x87, 0xf6, 0x93, 0x83, 0xd6, 0x6e, 0x39, 0xdb, 0x2b, 0x88, 0x0f, 0xdb,
	0xcd, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x5e, 0xab, 0x3f, 0x05, 0x0c, 0x00, 0x00,
}
