// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.15.1-0.20260724082201-6c49f1fd432b
// source: github.com/s4wave/spacewave/forge/lib/git/clone/config.proto

package forge_lib_git_clone

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	block "github.com/s4wave/spacewave/db/git/block"
	world "github.com/s4wave/spacewave/db/git/world"
)

// Config is the configuration for cloning Git repositories to a world.
// If the target object already exists, skips the step.
//
// Inputs:
//   - world: the target World engine or state.
//
// Outputs:
//   - repo: snapshot of the Repository object.
type Config struct {
	unknownFields []byte
	// ObjectKey is the object key to create as a Repo.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"objectKey,omitempty"`
	// CloneOpts are the args for the clone operation.
	CloneOpts *block.CloneOpts `protobuf:"bytes,2,opt,name=clone_opts,json=cloneOpts,proto3" json:"cloneOpts,omitempty"`
	// AuthOpts applies authentication to the operations.
	AuthOpts *block.AuthOpts `protobuf:"bytes,3,opt,name=auth_opts,json=authOpts,proto3" json:"authOpts,omitempty"`
	// WorktreeOpts are options for creating the worktree.
	// If cloneOpts.DisableCheckout is set, disables this step.
	WorktreeOpts *world.GitCreateWorktreeOp `protobuf:"bytes,4,opt,name=worktree_opts,json=worktreeOpts,proto3" json:"worktreeOpts,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
}

func (*Config) ProtoMessage() {}

func (x *Config) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Config) GetCloneOpts() *block.CloneOpts {
	if x != nil {
		return x.CloneOpts
	}
	return nil
}

func (x *Config) GetAuthOpts() *block.AuthOpts {
	if x != nil {
		return x.AuthOpts
	}
	return nil
}

func (x *Config) GetWorktreeOpts() *world.GitCreateWorktreeOp {
	if x != nil {
		return x.WorktreeOpts
	}
	return nil
}

func (m *Config) CloneVT() *Config {
	if m == nil {
		return (*Config)(nil)
	}
	r := new(Config)
	r.ObjectKey = m.ObjectKey
	r.CloneOpts = protobuf_go_lite.CloneVTValue(m.CloneOpts)
	r.AuthOpts = protobuf_go_lite.CloneVTValue(m.AuthOpts)
	r.WorktreeOpts = protobuf_go_lite.CloneVTValue(m.WorktreeOpts)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Config) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Config) EqualVT(that *Config) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ObjectKey != that.ObjectKey {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.CloneOpts, that.CloneOpts) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.AuthOpts, that.AuthOpts) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.WorktreeOpts, that.WorktreeOpts) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Config) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Config)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Config message to JSON.
func (x *Config) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.ObjectKey != "" || s.HasField("objectKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("objectKey")
		s.WriteString(x.ObjectKey)
	}
	if x.CloneOpts != nil || s.HasField("cloneOpts") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("cloneOpts")
		x.CloneOpts.MarshalProtoJSON(s.WithField("cloneOpts"))
	}
	if x.AuthOpts != nil || s.HasField("authOpts") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("authOpts")
		x.AuthOpts.MarshalProtoJSON(s.WithField("authOpts"))
	}
	if x.WorktreeOpts != nil || s.HasField("worktreeOpts") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("worktreeOpts")
		x.WorktreeOpts.MarshalProtoJSON(s.WithField("worktreeOpts"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Config to JSON.
func (x *Config) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Config message from JSON.
func (x *Config) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "object_key", "objectKey":
			s.AddField("object_key")
			x.ObjectKey = s.ReadString()
		case "clone_opts", "cloneOpts":
			if s.ReadNil() {
				x.CloneOpts = nil
				return
			}
			x.CloneOpts = &block.CloneOpts{}
			x.CloneOpts.UnmarshalProtoJSON(s.WithField("clone_opts", true))
		case "auth_opts", "authOpts":
			if s.ReadNil() {
				x.AuthOpts = nil
				return
			}
			x.AuthOpts = &block.AuthOpts{}
			x.AuthOpts.UnmarshalProtoJSON(s.WithField("auth_opts", true))
		case "worktree_opts", "worktreeOpts":
			if s.ReadNil() {
				x.WorktreeOpts = nil
				return
			}
			x.WorktreeOpts = &world.GitCreateWorktreeOp{}
			x.WorktreeOpts.UnmarshalProtoJSON(s.WithField("worktree_opts", true))
		}
	})
}

// UnmarshalJSON unmarshals the Config from JSON.
func (x *Config) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Config) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Config) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Config) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.WorktreeOpts != nil {
		size, err := m.WorktreeOpts.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.AuthOpts != nil {
		size, err := m.AuthOpts.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.CloneOpts != nil {
		size, err := m.CloneOpts.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ObjectKey) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ObjectKey)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Config) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ObjectKey)
	if m.CloneOpts != nil {
		l = m.CloneOpts.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.AuthOpts != nil {
		l = m.AuthOpts.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.WorktreeOpts != nil {
		l = m.WorktreeOpts.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (x *Config) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Config")
	if x.ObjectKey != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "object_key")
		protobuf_go_lite.TextWriteString(&sb, x.ObjectKey)
	}
	if x.CloneOpts != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "clone_opts")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.CloneOpts)
	}
	if x.AuthOpts != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "auth_opts")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.AuthOpts)
	}
	if x.WorktreeOpts != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "worktree_opts")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.WorktreeOpts)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Config) String() string {
	return x.MarshalProtoText()
}

func (m *Config) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectKey", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ObjectKey = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloneOpts", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.CloneOpts == nil {
				m.CloneOpts = &block.CloneOpts{}
			}
			if err := m.CloneOpts.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthOpts", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.AuthOpts == nil {
				m.AuthOpts = &block.AuthOpts{}
			}
			if err := m.AuthOpts.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorktreeOpts", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.WorktreeOpts == nil {
				m.WorktreeOpts = &world.GitCreateWorktreeOp{}
			}
			if err := m.WorktreeOpts.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
