//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.5
// source: github.com/s4wave/spacewave/sdk/provider/provider.proto

#include "provider_srpc.pb.hpp"

namespace s4wave::provider {

starpc::Error SRPCProviderResourceServiceClientImpl::GetProviderInfo(const s4wave::provider::GetProviderInfoRequest& in, s4wave::provider::GetProviderInfoResponse* out) {
  return cc_->ExecCall(service_id_, "GetProviderInfo", in, out);
}

starpc::Error SRPCProviderResourceServiceClientImpl::AccessProviderAccount(const s4wave::provider::AccessProviderAccountRequest& in, s4wave::provider::AccessProviderAccountResponse* out) {
  return cc_->ExecCall(service_id_, "AccessProviderAccount", in, out);
}

std::vector<std::string> SRPCProviderResourceServiceHandler::GetMethodIDs() const {
  return {
    "GetProviderInfo",
    "AccessProviderAccount",
  };
}

std::pair<bool, starpc::Error> SRPCProviderResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetProviderInfo") {
    s4wave::provider::GetProviderInfoRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::provider::GetProviderInfoResponse resp;
    err = impl_->GetProviderInfo(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "AccessProviderAccount") {
    s4wave::provider::AccessProviderAccountRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::provider::AccessProviderAccountResponse resp;
    err = impl_->AccessProviderAccount(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace s4wave::provider
