//go:build deps_only && cgo

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.5
// source: github.com/s4wave/spacewave/sdk/block/transaction/transaction.proto

#pragma once

#include <functional>
#include <memory>
#include <string>
#include <utility>

#include "srpc/starpc.hpp"

#include "transaction.pb.h"

namespace s4wave::block::transaction {

// Service ID for BlockTransactionResourceService
constexpr const char* kSRPCBlockTransactionResourceServiceServiceID = "s4wave.block.transaction.BlockTransactionResourceService";


// SRPCBlockTransactionResourceServiceClient is the client API for BlockTransactionResourceService service.
class SRPCBlockTransactionResourceServiceClient {
 public:
  virtual ~SRPCBlockTransactionResourceServiceClient() = default;

  // SRPCClient returns the underlying SRPC client.
  virtual starpc::Client* SRPCClient() = 0;

  // Write
  virtual starpc::Error Write(const s4wave::block::transaction::WriteRequest& in, s4wave::block::transaction::WriteResponse* out) = 0;
  // GetRootCursor
  virtual starpc::Error GetRootCursor(const s4wave::block::transaction::GetRootCursorRequest& in, s4wave::block::transaction::GetRootCursorResponse* out) = 0;
};

// SRPCBlockTransactionResourceServiceClientImpl implements SRPCBlockTransactionResourceServiceClient.
class SRPCBlockTransactionResourceServiceClientImpl : public SRPCBlockTransactionResourceServiceClient {
 public:
  explicit SRPCBlockTransactionResourceServiceClientImpl(starpc::Client* cc, const std::string& service_id = "")
      : cc_(cc), service_id_(service_id.empty() ? kSRPCBlockTransactionResourceServiceServiceID : service_id) {}

  starpc::Client* SRPCClient() override { return cc_; }

  // Write
  virtual starpc::Error Write(const s4wave::block::transaction::WriteRequest& in, s4wave::block::transaction::WriteResponse* out) override;
  // GetRootCursor
  virtual starpc::Error GetRootCursor(const s4wave::block::transaction::GetRootCursorRequest& in, s4wave::block::transaction::GetRootCursorResponse* out) override;

 private:
  starpc::Client* cc_;
  std::string service_id_;
};

// NewSRPCBlockTransactionResourceServiceClient creates a new client.
inline std::unique_ptr<SRPCBlockTransactionResourceServiceClient> NewSRPCBlockTransactionResourceServiceClient(starpc::Client* cc) {
  return std::make_unique<SRPCBlockTransactionResourceServiceClientImpl>(cc);
}

// SRPCBlockTransactionResourceServiceServer is the server API for BlockTransactionResourceService service.
class SRPCBlockTransactionResourceServiceServer {
 public:
  virtual ~SRPCBlockTransactionResourceServiceServer() = default;

  // Write
  virtual starpc::Error Write(const s4wave::block::transaction::WriteRequest& req, s4wave::block::transaction::WriteResponse* resp) = 0;
  // GetRootCursor
  virtual starpc::Error GetRootCursor(const s4wave::block::transaction::GetRootCursorRequest& req, s4wave::block::transaction::GetRootCursorResponse* resp) = 0;
};

// SRPCBlockTransactionResourceServiceHandler implements starpc::Handler for BlockTransactionResourceService.
class SRPCBlockTransactionResourceServiceHandler : public starpc::Handler {
 public:
  SRPCBlockTransactionResourceServiceHandler(SRPCBlockTransactionResourceServiceServer* impl, const std::string& service_id = "")
      : impl_(impl), service_id_(service_id.empty() ? kSRPCBlockTransactionResourceServiceServiceID : service_id) {}

  const std::string& GetServiceID() const override { return service_id_; }
  std::vector<std::string> GetMethodIDs() const override;
  std::pair<bool, starpc::Error> InvokeMethod(
      const std::string& service_id,
      const std::string& method_id,
      starpc::Stream* strm) override;

 private:
  SRPCBlockTransactionResourceServiceServer* impl_;
  std::string service_id_;
};

// NewSRPCBlockTransactionResourceServiceHandler creates a new handler for the given implementation.
inline std::unique_ptr<SRPCBlockTransactionResourceServiceHandler> NewSRPCBlockTransactionResourceServiceHandler(SRPCBlockTransactionResourceServiceServer* impl) {
  return std::make_unique<SRPCBlockTransactionResourceServiceHandler>(impl);
}

// SRPCRegisterBlockTransactionResourceService registers the server implementation with the mux.
// The returned handler must outlive the mux registration.
inline std::pair<std::unique_ptr<SRPCBlockTransactionResourceServiceHandler>, starpc::Error> SRPCRegisterBlockTransactionResourceService(starpc::Mux* mux, SRPCBlockTransactionResourceServiceServer* impl) {
  auto handler = NewSRPCBlockTransactionResourceServiceHandler(impl);
  starpc::Error err = mux->Register(handler.get());
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::move(handler), starpc::Error::OK};
}

}  // namespace s4wave::block::transaction
