// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.13.0
// source: github.com/s4wave/spacewave/core/forge/task/task.proto

package forge_task_ops

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	timestamppb "github.com/aperturerobotics/protobuf-go-lite/types/known/timestamppb"
)

// ForgeTaskCreateOp creates a Forge Task and optionally links it to a Job.
// Wraps CreateTaskWithTarget + graph linking in a single world op.
type ForgeTaskCreateOp struct {
	unknownFields []byte
	// TaskKey is the object key for the new Task.
	TaskKey string `protobuf:"bytes,1,opt,name=task_key,json=taskKey,proto3" json:"taskKey,omitempty"`
	// Name is the task name (must be a valid DNS label).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JobKey is the object key of the Job to link the Task to.
	// If empty, the Task is created without a Job link.
	JobKey string `protobuf:"bytes,3,opt,name=job_key,json=jobKey,proto3" json:"jobKey,omitempty"`
	// Timestamp is the creation timestamp.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ForgeTaskCreateOp) Reset() {
	*x = ForgeTaskCreateOp{}
}

func (*ForgeTaskCreateOp) ProtoMessage() {}

func (x *ForgeTaskCreateOp) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *ForgeTaskCreateOp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForgeTaskCreateOp) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *ForgeTaskCreateOp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (m *ForgeTaskCreateOp) CloneVT() *ForgeTaskCreateOp {
	if m == nil {
		return (*ForgeTaskCreateOp)(nil)
	}
	r := new(ForgeTaskCreateOp)
	r.TaskKey = m.TaskKey
	r.Name = m.Name
	r.JobKey = m.JobKey
	if rhs := m.Timestamp; rhs != nil {
		r.Timestamp = rhs.CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ForgeTaskCreateOp) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *ForgeTaskCreateOp) EqualVT(that *ForgeTaskCreateOp) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TaskKey != that.TaskKey {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.JobKey != that.JobKey {
		return false
	}
	if !this.Timestamp.EqualVT(that.Timestamp) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ForgeTaskCreateOp) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ForgeTaskCreateOp)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ForgeTaskCreateOp message to JSON.
func (x *ForgeTaskCreateOp) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.TaskKey != "" || s.HasField("taskKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("taskKey")
		s.WriteString(x.TaskKey)
	}
	if x.Name != "" || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	if x.JobKey != "" || s.HasField("jobKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("jobKey")
		s.WriteString(x.JobKey)
	}
	if x.Timestamp != nil || s.HasField("timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestamp")
		x.Timestamp.MarshalProtoJSON(s.WithField("timestamp"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ForgeTaskCreateOp to JSON.
func (x *ForgeTaskCreateOp) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ForgeTaskCreateOp message from JSON.
func (x *ForgeTaskCreateOp) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "task_key", "taskKey":
			s.AddField("task_key")
			x.TaskKey = s.ReadString()
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		case "job_key", "jobKey":
			s.AddField("job_key")
			x.JobKey = s.ReadString()
		case "timestamp":
			if s.ReadNil() {
				x.Timestamp = nil
				return
			}
			x.Timestamp = &timestamppb.Timestamp{}
			x.Timestamp.UnmarshalProtoJSON(s.WithField("timestamp", true))
		}
	})
}

// UnmarshalJSON unmarshals the ForgeTaskCreateOp from JSON.
func (x *ForgeTaskCreateOp) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *ForgeTaskCreateOp) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForgeTaskCreateOp) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ForgeTaskCreateOp) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Timestamp != nil {
		size, err := m.Timestamp.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if len(m.JobKey) > 0 {
		i -= len(m.JobKey)
		copy(dAtA[i:], m.JobKey)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.JobKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TaskKey) > 0 {
		i -= len(m.TaskKey)
		copy(dAtA[i:], m.TaskKey)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.TaskKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ForgeTaskCreateOp) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskKey)
	if l > 0 {
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	l = len(m.JobKey)
	if l > 0 {
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.SizeVT()
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (x *ForgeTaskCreateOp) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("ForgeTaskCreateOp {")
	if x.TaskKey != "" {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("task_key: ")
		sb.WriteString(strconv.Quote(x.TaskKey))
	}
	if x.Name != "" {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("name: ")
		sb.WriteString(strconv.Quote(x.Name))
	}
	if x.JobKey != "" {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("job_key: ")
		sb.WriteString(strconv.Quote(x.JobKey))
	}
	if x.Timestamp != nil {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("timestamp: ")
		sb.WriteString(x.Timestamp.MarshalProtoText())
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *ForgeTaskCreateOp) String() string {
	return x.MarshalProtoText()
}

func (m *ForgeTaskCreateOp) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForgeTaskCreateOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForgeTaskCreateOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskKey", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobKey", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &timestamppb.Timestamp{}
			}
			if err := m.Timestamp.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
