// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/bldr/plugin/host/web/config.proto (package plugin.host.web, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, Message } from '@aptre/protobuf-es-lite'
import { Config as Config$1 } from '../controller/config.pb.js'

export const protobufPackage = 'plugin.host.web'

/**
 * Config is the WebWorker PluginHost controller configuration.
 *
 * @generated from message plugin.host.web.Config
 */
export type Config = Message<{
  /**
   * HostConfig configures the plugin host controller.
   *
   * @generated from field: plugin.host.controller.Config host_config = 1;
   */
  hostConfig?: Config$1
  /**
   * WebRuntimeId is the identifier of the web runtime.
   *
   * @generated from field: string web_runtime_id = 2;
   */
  webRuntimeId?: string
}>

export const Config: MessageType<Config> = createMessageType({
  typeName: 'plugin.host.web.Config',
  fields: [
    { no: 1, name: 'host_config', kind: 'message', T: () => Config$1 },
    {
      no: 2,
      name: 'web_runtime_id',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
