// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/s4wave/spacewave/core/session/session.proto (package session, syntax proto3)
/* eslint-disable */

import { createEnumType } from '@aptre/protobuf-es-lite/enum'
import { ProviderResourceRef } from '../provider/provider.pb.js'
import type { MessageType } from '@aptre/protobuf-es-lite/message'
import { createMessageType } from '@aptre/protobuf-es-lite/message'
import type { PartialFieldInfo } from '@aptre/protobuf-es-lite/field'
import { ScalarType } from '@aptre/protobuf-es-lite/scalar'

export const protobufPackage = 'session'

/**
 * SessionType identifies the type of session.
 *
 * @generated from enum session.SessionType
 */
export enum SessionType {
  /**
   * SESSION_TYPE_UNKNOWN is the default unknown session type.
   *
   * @generated from enum value: SESSION_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * SESSION_TYPE_USER is a human user session.
   *
   * @generated from enum value: SESSION_TYPE_USER = 1;
   */
  USER = 1,

  /**
   * SESSION_TYPE_APP is a third-party application session.
   *
   * @generated from enum value: SESSION_TYPE_APP = 2;
   */
  APP = 2,

  /**
   * SESSION_TYPE_DEVICE is a linked device session.
   *
   * @generated from enum value: SESSION_TYPE_DEVICE = 3;
   */
  DEVICE = 3,
}

export const SessionType_Enum = /* @__PURE__ */ createEnumType(
  'session.SessionType',
  [
    [0, 'SESSION_TYPE_UNKNOWN'],
    [1, 'SESSION_TYPE_USER'],
    [2, 'SESSION_TYPE_APP'],
    [3, 'SESSION_TYPE_DEVICE'],
  ],
)

/**
 * SessionLockMode identifies how a session private key is protected at rest.
 *
 * @generated from enum session.SessionLockMode
 */
export enum SessionLockMode {
  /**
   * SESSION_LOCK_MODE_AUTO_UNLOCK is encrypted with volume-derived key.
   *
   * @generated from enum value: SESSION_LOCK_MODE_AUTO_UNLOCK = 0;
   */
  AUTO_UNLOCK = 0,

  /**
   * SESSION_LOCK_MODE_PIN_ENCRYPTED is encrypted with PIN-derived key.
   *
   * @generated from enum value: SESSION_LOCK_MODE_PIN_ENCRYPTED = 1;
   */
  PIN_ENCRYPTED = 1,
}

export const SessionLockMode_Enum = /* @__PURE__ */ createEnumType(
  'session.SessionLockMode',
  [
    [0, 'SESSION_LOCK_MODE_AUTO_UNLOCK'],
    [1, 'SESSION_LOCK_MODE_PIN_ENCRYPTED'],
  ],
)

/**
 * SessionRecoveryState identifies whether a PIN-locked session has a reset path.
 *
 * @generated from enum session.SessionRecoveryState
 */
export enum SessionRecoveryState {
  /**
   * SESSION_RECOVERY_STATE_UNKNOWN means the reset path has not been inspected.
   *
   * @generated from enum value: SESSION_RECOVERY_STATE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * SESSION_RECOVERY_STATE_AVAILABLE means ResetSession can recover without the current PIN.
   *
   * @generated from enum value: SESSION_RECOVERY_STATE_AVAILABLE = 1;
   */
  AVAILABLE = 1,

  /**
   * SESSION_RECOVERY_STATE_UNAVAILABLE means the current PIN is the only unlock method.
   *
   * @generated from enum value: SESSION_RECOVERY_STATE_UNAVAILABLE = 2;
   */
  UNAVAILABLE = 2,
}

export const SessionRecoveryState_Enum = /* @__PURE__ */ createEnumType(
  'session.SessionRecoveryState',
  [
    [0, 'SESSION_RECOVERY_STATE_UNKNOWN'],
    [1, 'SESSION_RECOVERY_STATE_AVAILABLE'],
    [2, 'SESSION_RECOVERY_STATE_UNAVAILABLE'],
  ],
)

/**
 * SessionRef is a reference to a session managed by a provider.
 *
 * @generated from message session.SessionRef
 */
export interface SessionRef {
  /**
   * ProviderResourceRef is the reference to the resource on the provider.
   * Contains the session ID, provider ID and provider account ID.
   * The session ID is the ID for this particular session.
   * The provider account ID is the ID for this user account.
   *
   * @generated from field: provider.ProviderResourceRef provider_resource_ref = 1;
   */
  providerResourceRef?: ProviderResourceRef
}

export const SessionRef: MessageType<SessionRef> =
  /* @__PURE__ */ createMessageType({
    typeName: 'session.SessionRef',
    fields: [
      {
        no: 1,
        name: 'provider_resource_ref',
        kind: 'message',
        T: () => ProviderResourceRef,
      },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * SessionListEntry is an entry in the local session list.
 *
 * @generated from message session.SessionListEntry
 */
export interface SessionListEntry {
  /**
   * SessionIndex is the index of the session.
   * The session is accessible at /u/{session-index}/...
   *
   * @generated from field: uint32 session_index = 1;
   */
  sessionIndex?: number
  /**
   * SessionRef is the reference to the session.
   *
   * @generated from field: session.SessionRef session_ref = 2;
   */
  sessionRef?: SessionRef
}

export const SessionListEntry: MessageType<SessionListEntry> =
  /* @__PURE__ */ createMessageType({
    typeName: 'session.SessionListEntry',
    fields: [
      { no: 1, name: 'session_index', kind: 'scalar', T: ScalarType.UINT32 },
      { no: 2, name: 'session_ref', kind: 'message', T: () => SessionRef },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * SessionMetadata contains display and pre-mount lock information for a session.
 * Stored in the session controller ObjectStore at sessions/meta/{sessionID}.
 *
 * @generated from message session.SessionMetadata
 */
export interface SessionMetadata {
  /**
   * DisplayName is the display name for the session (username/entity_id).
   *
   * @generated from field: string display_name = 1;
   */
  displayName?: string
  /**
   * ProviderDisplayName is the display name of the provider.
   *
   * @generated from field: string provider_display_name = 2;
   */
  providerDisplayName?: string
  /**
   * ProviderAccountId is the provider account identifier.
   *
   * @generated from field: string provider_account_id = 3;
   */
  providerAccountId?: string
  /**
   * LockMode is set at registration and updated by SetLockMode.
   * Used as a pre-mount hint to show the PIN overlay before the session mounts.
   * The authoritative lock state comes from WatchLockState on the mounted session.
   *
   * @generated from field: session.SessionLockMode lock_mode = 4;
   */
  lockMode?: SessionLockMode
  /**
   * CreatedAt is the creation timestamp in milliseconds since epoch.
   *
   * @generated from field: int64 created_at = 5;
   */
  createdAt?: bigint
  /**
   * CloudAccountId is the cloud account ULID for free local sessions.
   * Set when a local session is created with a cloud identity.
   *
   * @generated from field: string cloud_account_id = 7;
   */
  cloudAccountId?: string
  /**
   * CloudEntityId is the cloud username for free local sessions.
   *
   * @generated from field: string cloud_entity_id = 8;
   */
  cloudEntityId?: string
  /**
   * ProviderId is the provider type identifier (e.g. "spacewave", "local").
   *
   * @generated from field: string provider_id = 10;
   */
  providerId?: string
  /**
   * RecoveryState reports whether the PIN reset path can recover this session.
   *
   * @generated from field: session.SessionRecoveryState recovery_state = 11;
   */
  recoveryState?: SessionRecoveryState
}

export const SessionMetadata: MessageType<SessionMetadata> =
  /* @__PURE__ */ createMessageType({
    typeName: 'session.SessionMetadata',
    fields: [
      { no: 1, name: 'display_name', kind: 'scalar', T: ScalarType.STRING },
      {
        no: 2,
        name: 'provider_display_name',
        kind: 'scalar',
        T: ScalarType.STRING,
      },
      {
        no: 3,
        name: 'provider_account_id',
        kind: 'scalar',
        T: ScalarType.STRING,
      },
      { no: 4, name: 'lock_mode', kind: 'enum', T: SessionLockMode_Enum },
      { no: 5, name: 'created_at', kind: 'scalar', T: ScalarType.INT64 },
      { no: 7, name: 'cloud_account_id', kind: 'scalar', T: ScalarType.STRING },
      { no: 8, name: 'cloud_entity_id', kind: 'scalar', T: ScalarType.STRING },
      { no: 10, name: 'provider_id', kind: 'scalar', T: ScalarType.STRING },
      {
        no: 11,
        name: 'recovery_state',
        kind: 'enum',
        T: SessionRecoveryState_Enum,
      },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * EntityKeypair is a keypair associated with an entity for authentication.
 *
 * @generated from message session.EntityKeypair
 */
export interface EntityKeypair {
  /**
   * PeerId is the peer ID associated with this keypair.
   *
   * @generated from field: string peer_id = 1;
   */
  peerId?: string
  /**
   * AuthMethod is the authentication method.
   *
   * @generated from field: string auth_method = 2;
   */
  authMethod?: string
  /**
   * AuthParams is optional authentication parameters.
   *
   * @generated from field: bytes auth_params = 3;
   */
  authParams?: Uint8Array
}

export const EntityKeypair: MessageType<EntityKeypair> =
  /* @__PURE__ */ createMessageType({
    typeName: 'session.EntityKeypair',
    fields: [
      { no: 1, name: 'peer_id', kind: 'scalar', T: ScalarType.STRING },
      { no: 2, name: 'auth_method', kind: 'scalar', T: ScalarType.STRING },
      { no: 3, name: 'auth_params', kind: 'scalar', T: ScalarType.BYTES },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * EntityCredential is a credential for deriving an entity private key.
 * Used by local in-process RPCs where the credential never crosses a
 * network boundary (Go WASM and TS share the same browser process).
 *
 * @generated from message session.EntityCredential
 */
export interface EntityCredential {
  /**
   * @generated from oneof session.EntityCredential.credential
   */
  credential?:
    | {
        value?: undefined
        case: undefined
      }
    | {
        /**
         * Password derives the entity key via triplesec(username, password).
         *
         * @generated from field: string password = 1;
         */
        value: string
        case: 'password'
      }
    | {
        /**
         * PemPrivateKey is the entity private key in PEM format.
         *
         * @generated from field: bytes pem_private_key = 2;
         */
        value: Uint8Array
        case: 'pemPrivateKey'
      }
}

export const EntityCredential: MessageType<EntityCredential> =
  /* @__PURE__ */ createMessageType({
    typeName: 'session.EntityCredential',
    fields: [
      {
        no: 1,
        name: 'password',
        kind: 'scalar',
        T: ScalarType.STRING,
        oneof: 'credential',
      },
      {
        no: 2,
        name: 'pem_private_key',
        kind: 'scalar',
        T: ScalarType.BYTES,
        oneof: 'credential',
      },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })
