// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/hydra/block/store/ristretto/ristretto.proto (package block.store.ristretto, syntax proto3)
/* eslint-disable */

import { Config as Config$1 } from '../../../store/kvtx/ristretto/ristretto.pb.js'
import { Config as Config$2 } from '../../../store/kvkey/kvkey.pb.js'
import type { HashType } from '@go/github.com/aperturerobotics/bifrost/hash/hash.pb.js'
import { HashType_Enum } from '@go/github.com/aperturerobotics/bifrost/hash/hash.pb.js'
import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, ScalarType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'block.store.ristretto'

/**
 * Config configures the Ristretto block cache controller.
 *
 * @generated from message block.store.ristretto.Config
 */
export interface Config {
  /**
   * BlockStoreId is the block store id to use on the bus.
   *
   * @generated from field: string block_store_id = 1;
   */
  blockStoreId?: string
  /**
   * Ristretto configures the ristretto store.
   *
   * @generated from field: store.kvtx.ristretto.Config ristretto = 2;
   */
  ristretto?: Config$1
  /**
   * KvKeyOpts are key/value key constants.
   * Optional.
   *
   * @generated from field: store.kvkey.Config kv_key_opts = 3;
   */
  kvKeyOpts?: Config$2
  /**
   * ForceHashType forces writing the given hash type to the store.
   * If unset, accepts any hash type.
   *
   * @generated from field: hash.HashType force_hash_type = 4;
   */
  forceHashType?: HashType
  /**
   * HashGet enables hashing values for Get requests.
   * This reduces performance but ensures data integrity.
   * As ristretto is an in-memory cache, it shouldn't be necessary to use this.
   *
   * @generated from field: bool hash_get = 8;
   */
  hashGet?: boolean
  /**
   * BucketIds is a list of bucket ids to serve LookupBlockFromNetwork directives.
   *
   * @generated from field: repeated string bucket_ids = 5;
   */
  bucketIds?: string[]
  /**
   * SkipNotFound skips returning a value if the block was not found.
   *
   * @generated from field: bool skip_not_found = 6;
   */
  skipNotFound?: boolean
  /**
   * Verbose enables verbose logging of the block store.
   *
   * @generated from field: bool verbose = 7;
   */
  verbose?: boolean
}

// Config contains the message type declaration for Config.
export const Config: MessageType<Config> = createMessageType({
  typeName: 'block.store.ristretto.Config',
  fields: [
    { no: 1, name: 'block_store_id', kind: 'scalar', T: ScalarType.STRING },
    { no: 2, name: 'ristretto', kind: 'message', T: () => Config$1 },
    { no: 3, name: 'kv_key_opts', kind: 'message', T: () => Config$2 },
    { no: 4, name: 'force_hash_type', kind: 'enum', T: HashType_Enum },
    { no: 8, name: 'hash_get', kind: 'scalar', T: ScalarType.BOOL },
    {
      no: 5,
      name: 'bucket_ids',
      kind: 'scalar',
      T: ScalarType.STRING,
      repeated: true,
    },
    { no: 6, name: 'skip_not_found', kind: 'scalar', T: ScalarType.BOOL },
    { no: 7, name: 'verbose', kind: 'scalar', T: ScalarType.BOOL },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
