// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.16.0
// source: github.com/s4wave/spacewave/core/forge/exec/plugin.proto

package space_exec

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	value "github.com/s4wave/spacewave/forge/value"
)

// PluginExecConfig configures the generic plugin execution bridge.
type PluginExecConfig struct {
	unknownFields []byte
	// PluginId is the plugin to load before executing.
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"pluginId,omitempty"`
	// ControllerId is the plugin-owned execution controller id to invoke.
	ControllerId string `protobuf:"bytes,2,opt,name=controller_id,json=controllerId,proto3" json:"controllerId,omitempty"`
	// ControllerConfig is opaque config bytes for the plugin-owned controller.
	ControllerConfig []byte `protobuf:"bytes,3,opt,name=controller_config,json=controllerConfig,proto3" json:"controllerConfig,omitempty"`
}

func (x *PluginExecConfig) Reset() {
	*x = PluginExecConfig{}
}

func (*PluginExecConfig) ProtoMessage() {}

func (x *PluginExecConfig) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginExecConfig) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *PluginExecConfig) GetControllerConfig() []byte {
	if x != nil {
		return x.ControllerConfig
	}
	return nil
}

// PluginExecRequest asks a loaded plugin to execute a controller.
type PluginExecRequest struct {
	unknownFields []byte
	// ControllerId is the plugin-owned execution controller id to invoke.
	ControllerId string `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controllerId,omitempty"`
	// ControllerConfig is opaque config bytes for the plugin-owned controller.
	ControllerConfig []byte `protobuf:"bytes,2,opt,name=controller_config,json=controllerConfig,proto3" json:"controllerConfig,omitempty"`
	// Inputs are the Forge execution inputs.
	Inputs []*value.Value `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *PluginExecRequest) Reset() {
	*x = PluginExecRequest{}
}

func (*PluginExecRequest) ProtoMessage() {}

func (x *PluginExecRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *PluginExecRequest) GetControllerConfig() []byte {
	if x != nil {
		return x.ControllerConfig
	}
	return nil
}

func (x *PluginExecRequest) GetInputs() []*value.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// PluginExecLog is a log entry emitted by a plugin execution controller.
type PluginExecLog struct {
	unknownFields []byte
	// Level is the log severity.
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// Message is the log message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PluginExecLog) Reset() {
	*x = PluginExecLog{}
}

func (*PluginExecLog) ProtoMessage() {}

func (x *PluginExecLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PluginExecLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PluginExecOutputFile is one captured output file from a plugin controller.
type PluginExecOutputFile struct {
	unknownFields []byte
	// Path is the slash-separated path relative to the output root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Data is the file contents.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PluginExecOutputFile) Reset() {
	*x = PluginExecOutputFile{}
}

func (*PluginExecOutputFile) ProtoMessage() {}

func (x *PluginExecOutputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginExecOutputFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PluginExecResponse contains controller logs, outputs, and optional failure.
type PluginExecResponse struct {
	unknownFields []byte
	// Logs are execution logs to append to the Forge execution.
	Logs []*PluginExecLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// Outputs are Forge execution outputs to set.
	Outputs []*value.Value `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Error is the plugin execution failure message, if any.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// OutputFiles are files to import as the default UnixFS "output" value.
	OutputFiles []*PluginExecOutputFile `protobuf:"bytes,4,rep,name=output_files,json=outputFiles,proto3" json:"outputFiles,omitempty"`
}

func (x *PluginExecResponse) Reset() {
	*x = PluginExecResponse{}
}

func (*PluginExecResponse) ProtoMessage() {}

func (x *PluginExecResponse) GetLogs() []*PluginExecLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *PluginExecResponse) GetOutputs() []*value.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *PluginExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PluginExecResponse) GetOutputFiles() []*PluginExecOutputFile {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

func (m *PluginExecConfig) CloneVT() *PluginExecConfig {
	if m == nil {
		return (*PluginExecConfig)(nil)
	}
	r := new(PluginExecConfig)
	r.PluginId = m.PluginId
	r.ControllerId = m.ControllerId
	r.ControllerConfig = protobuf_go_lite.CloneBytes(m.ControllerConfig)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *PluginExecConfig) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *PluginExecRequest) CloneVT() *PluginExecRequest {
	if m == nil {
		return (*PluginExecRequest)(nil)
	}
	r := new(PluginExecRequest)
	r.ControllerId = m.ControllerId
	r.ControllerConfig = protobuf_go_lite.CloneBytes(m.ControllerConfig)
	r.Inputs = protobuf_go_lite.CloneVTSlice(m.Inputs)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *PluginExecRequest) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *PluginExecLog) CloneVT() *PluginExecLog {
	if m == nil {
		return (*PluginExecLog)(nil)
	}
	r := new(PluginExecLog)
	r.Level = m.Level
	r.Message = m.Message
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *PluginExecLog) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *PluginExecOutputFile) CloneVT() *PluginExecOutputFile {
	if m == nil {
		return (*PluginExecOutputFile)(nil)
	}
	r := new(PluginExecOutputFile)
	r.Path = m.Path
	r.Data = protobuf_go_lite.CloneBytes(m.Data)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *PluginExecOutputFile) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *PluginExecResponse) CloneVT() *PluginExecResponse {
	if m == nil {
		return (*PluginExecResponse)(nil)
	}
	r := new(PluginExecResponse)
	r.Error = m.Error
	r.Logs = protobuf_go_lite.CloneVTSlice(m.Logs)
	r.Outputs = protobuf_go_lite.CloneVTSlice(m.Outputs)
	r.OutputFiles = protobuf_go_lite.CloneVTSlice(m.OutputFiles)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *PluginExecResponse) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *PluginExecConfig) EqualVT(that *PluginExecConfig) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.PluginId != that.PluginId {
		return false
	}
	if this.ControllerId != that.ControllerId {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.ControllerConfig, that.ControllerConfig) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PluginExecConfig) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*PluginExecConfig)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *PluginExecRequest) EqualVT(that *PluginExecRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ControllerId != that.ControllerId {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.ControllerConfig, that.ControllerConfig) {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Inputs, that.Inputs, func() *value.Value { return &value.Value{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PluginExecRequest) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*PluginExecRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *PluginExecLog) EqualVT(that *PluginExecLog) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Level != that.Level {
		return false
	}
	if this.Message != that.Message {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PluginExecLog) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*PluginExecLog)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *PluginExecOutputFile) EqualVT(that *PluginExecOutputFile) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Path != that.Path {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.Data, that.Data) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PluginExecOutputFile) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*PluginExecOutputFile)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *PluginExecResponse) EqualVT(that *PluginExecResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Logs, that.Logs, func() *PluginExecLog { return &PluginExecLog{} }) {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Outputs, that.Outputs, func() *value.Value { return &value.Value{} }) {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.OutputFiles, that.OutputFiles, func() *PluginExecOutputFile { return &PluginExecOutputFile{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PluginExecResponse) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*PluginExecResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the PluginExecConfig message to JSON.
func (x *PluginExecConfig) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.PluginId != "" || s.HasField("pluginId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("pluginId")
		s.WriteString(x.PluginId)
	}
	if x.ControllerId != "" || s.HasField("controllerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("controllerId")
		s.WriteString(x.ControllerId)
	}
	if len(x.ControllerConfig) > 0 || s.HasField("controllerConfig") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("controllerConfig")
		s.WriteBytes(x.ControllerConfig)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the PluginExecConfig to JSON.
func (x *PluginExecConfig) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the PluginExecConfig message from JSON.
func (x *PluginExecConfig) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "plugin_id", "pluginId":
			s.AddField("plugin_id")
			x.PluginId = s.ReadString()
		case "controller_id", "controllerId":
			s.AddField("controller_id")
			x.ControllerId = s.ReadString()
		case "controller_config", "controllerConfig":
			s.AddField("controller_config")
			x.ControllerConfig = s.ReadBytes()
		}
	})
}

// UnmarshalJSON unmarshals the PluginExecConfig from JSON.
func (x *PluginExecConfig) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the PluginExecRequest message to JSON.
func (x *PluginExecRequest) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.ControllerId != "" || s.HasField("controllerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("controllerId")
		s.WriteString(x.ControllerId)
	}
	if len(x.ControllerConfig) > 0 || s.HasField("controllerConfig") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("controllerConfig")
		s.WriteBytes(x.ControllerConfig)
	}
	if len(x.Inputs) > 0 || s.HasField("inputs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("inputs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Inputs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("inputs"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the PluginExecRequest to JSON.
func (x *PluginExecRequest) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the PluginExecRequest message from JSON.
func (x *PluginExecRequest) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "controller_id", "controllerId":
			s.AddField("controller_id")
			x.ControllerId = s.ReadString()
		case "controller_config", "controllerConfig":
			s.AddField("controller_config")
			x.ControllerConfig = s.ReadBytes()
		case "inputs":
			s.AddField("inputs")
			if s.ReadNil() {
				x.Inputs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Inputs = append(x.Inputs, nil)
					return
				}
				v := &value.Value{}
				v.UnmarshalProtoJSON(s.WithField("inputs", false))
				if s.Err() != nil {
					return
				}
				x.Inputs = append(x.Inputs, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the PluginExecRequest from JSON.
func (x *PluginExecRequest) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the PluginExecLog message to JSON.
func (x *PluginExecLog) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Level != "" || s.HasField("level") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("level")
		s.WriteString(x.Level)
	}
	if x.Message != "" || s.HasField("message") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("message")
		s.WriteString(x.Message)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the PluginExecLog to JSON.
func (x *PluginExecLog) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the PluginExecLog message from JSON.
func (x *PluginExecLog) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "level":
			s.AddField("level")
			x.Level = s.ReadString()
		case "message":
			s.AddField("message")
			x.Message = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the PluginExecLog from JSON.
func (x *PluginExecLog) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the PluginExecOutputFile message to JSON.
func (x *PluginExecOutputFile) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Path != "" || s.HasField("path") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("path")
		s.WriteString(x.Path)
	}
	if len(x.Data) > 0 || s.HasField("data") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("data")
		s.WriteBytes(x.Data)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the PluginExecOutputFile to JSON.
func (x *PluginExecOutputFile) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the PluginExecOutputFile message from JSON.
func (x *PluginExecOutputFile) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "path":
			s.AddField("path")
			x.Path = s.ReadString()
		case "data":
			s.AddField("data")
			x.Data = s.ReadBytes()
		}
	})
}

// UnmarshalJSON unmarshals the PluginExecOutputFile from JSON.
func (x *PluginExecOutputFile) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the PluginExecResponse message to JSON.
func (x *PluginExecResponse) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Logs) > 0 || s.HasField("logs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("logs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Logs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("logs"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Outputs) > 0 || s.HasField("outputs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("outputs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Outputs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("outputs"))
		}
		s.WriteArrayEnd()
	}
	if x.Error != "" || s.HasField("error") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		s.WriteString(x.Error)
	}
	if len(x.OutputFiles) > 0 || s.HasField("outputFiles") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("outputFiles")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.OutputFiles {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("outputFiles"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the PluginExecResponse to JSON.
func (x *PluginExecResponse) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the PluginExecResponse message from JSON.
func (x *PluginExecResponse) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "logs":
			s.AddField("logs")
			if s.ReadNil() {
				x.Logs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Logs = append(x.Logs, nil)
					return
				}
				v := &PluginExecLog{}
				v.UnmarshalProtoJSON(s.WithField("logs", false))
				if s.Err() != nil {
					return
				}
				x.Logs = append(x.Logs, v)
			})
		case "outputs":
			s.AddField("outputs")
			if s.ReadNil() {
				x.Outputs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Outputs = append(x.Outputs, nil)
					return
				}
				v := &value.Value{}
				v.UnmarshalProtoJSON(s.WithField("outputs", false))
				if s.Err() != nil {
					return
				}
				x.Outputs = append(x.Outputs, v)
			})
		case "error":
			s.AddField("error")
			x.Error = s.ReadString()
		case "output_files", "outputFiles":
			s.AddField("output_files")
			if s.ReadNil() {
				x.OutputFiles = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.OutputFiles = append(x.OutputFiles, nil)
					return
				}
				v := &PluginExecOutputFile{}
				v.UnmarshalProtoJSON(s.WithField("output_files", false))
				if s.Err() != nil {
					return
				}
				x.OutputFiles = append(x.OutputFiles, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the PluginExecResponse from JSON.
func (x *PluginExecResponse) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *PluginExecConfig) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PluginExecConfig) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *PluginExecConfig) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.ControllerConfig) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.ControllerConfig)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ControllerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ControllerId)
		i--
		dAtA[i] = 0x12
	}
	if len(m.PluginId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.PluginId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PluginExecRequest) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PluginExecRequest) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *PluginExecRequest) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Inputs) > 0 {
		for iNdEx := len(m.Inputs) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Inputs[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ControllerConfig) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.ControllerConfig)
		i--
		dAtA[i] = 0x12
	}
	if len(m.ControllerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ControllerId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PluginExecLog) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PluginExecLog) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *PluginExecLog) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Message) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Message)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Level) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Level)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PluginExecOutputFile) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PluginExecOutputFile) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *PluginExecOutputFile) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Data) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.Data)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Path) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Path)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PluginExecResponse) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PluginExecResponse) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *PluginExecResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.OutputFiles) > 0 {
		for iNdEx := len(m.OutputFiles) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.OutputFiles[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Error) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Outputs[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Logs) > 0 {
		for iNdEx := len(m.Logs) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Logs[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PluginExecConfig) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.PluginId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ControllerId)
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.ControllerConfig)
	n += len(m.unknownFields)
	return n
}

func (m *PluginExecRequest) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ControllerId)
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.ControllerConfig)
	for _, e := range m.Inputs {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *PluginExecLog) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Level)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Message)
	n += len(m.unknownFields)
	return n
}

func (m *PluginExecOutputFile) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Path)
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.Data)
	n += len(m.unknownFields)
	return n
}

func (m *PluginExecResponse) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	for _, e := range m.Logs {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	for _, e := range m.Outputs {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Error)
	for _, e := range m.OutputFiles {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (x *PluginExecConfig) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "PluginExecConfig")
	if x.PluginId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "plugin_id")
		protobuf_go_lite.TextWriteString(&sb, x.PluginId)
	}
	if x.ControllerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "controller_id")
		protobuf_go_lite.TextWriteString(&sb, x.ControllerId)
	}
	if len(x.ControllerConfig) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "controller_config")
		protobuf_go_lite.TextWriteBytes(&sb, x.ControllerConfig)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *PluginExecConfig) String() string {
	return x.MarshalProtoText()
}

func (x *PluginExecRequest) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "PluginExecRequest")
	if x.ControllerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "controller_id")
		protobuf_go_lite.TextWriteString(&sb, x.ControllerId)
	}
	if len(x.ControllerConfig) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "controller_config")
		protobuf_go_lite.TextWriteBytes(&sb, x.ControllerConfig)
	}
	if len(x.Inputs) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "inputs")
		for i, v := range x.Inputs {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &value.Value{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *PluginExecRequest) String() string {
	return x.MarshalProtoText()
}

func (x *PluginExecLog) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "PluginExecLog")
	if x.Level != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "level")
		protobuf_go_lite.TextWriteString(&sb, x.Level)
	}
	if x.Message != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "message")
		protobuf_go_lite.TextWriteString(&sb, x.Message)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *PluginExecLog) String() string {
	return x.MarshalProtoText()
}

func (x *PluginExecOutputFile) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "PluginExecOutputFile")
	if x.Path != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "path")
		protobuf_go_lite.TextWriteString(&sb, x.Path)
	}
	if len(x.Data) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "data")
		protobuf_go_lite.TextWriteBytes(&sb, x.Data)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *PluginExecOutputFile) String() string {
	return x.MarshalProtoText()
}

func (x *PluginExecResponse) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "PluginExecResponse")
	if len(x.Logs) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "logs")
		for i, v := range x.Logs {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &PluginExecLog{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.Outputs) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "outputs")
		for i, v := range x.Outputs {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &value.Value{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.Error != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, x.Error)
	}
	if len(x.OutputFiles) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "output_files")
		for i, v := range x.OutputFiles {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &PluginExecOutputFile{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *PluginExecResponse) String() string {
	return x.MarshalProtoText()
}

func (m *PluginExecConfig) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PluginExecConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PluginExecConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PluginId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.PluginId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ControllerId = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerConfig", wireType)
			}
			m.ControllerConfig, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.ControllerConfig, dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *PluginExecRequest) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PluginExecRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PluginExecRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ControllerId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerConfig", wireType)
			}
			m.ControllerConfig, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.ControllerConfig, dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Inputs = append(m.Inputs, &value.Value{})
			if err := m.Inputs[len(m.Inputs)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *PluginExecLog) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PluginExecLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PluginExecLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Level = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Message = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *PluginExecOutputFile) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PluginExecOutputFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PluginExecOutputFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Path = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			m.Data, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.Data, dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *PluginExecResponse) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PluginExecResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PluginExecResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logs", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Logs = append(m.Logs, &PluginExecLog{})
			if err := m.Logs[len(m.Logs)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Outputs = append(m.Outputs, &value.Value{})
			if err := m.Outputs[len(m.Outputs)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Error = v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputFiles", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.OutputFiles = append(m.OutputFiles, &PluginExecOutputFile{})
			if err := m.OutputFiles[len(m.OutputFiles)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
