// @generated
// This file is @generated by prost-build.
/// Config configures the project file watcher.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    /// ConfigPath is the path to load the bldr.yaml configuration.
    /// If the path is empty, starts the project controller with a blank config.
    #[prost(string, tag="1")]
    pub config_path: ::prost::alloc::string::String,
    /// ProjectControllerConfig configures the project controller.
    /// The loaded project controller config will be merged into this config.
    #[prost(message, optional, tag="2")]
    pub project_controller_config: ::core::option::Option<super::controller::Config>,
    /// DisableWatch disables watching the file (loads once only).
    #[prost(bool, tag="3")]
    pub disable_watch: bool,
}
// @@protoc_insertion_point(module)
