//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.49.5
// source: github.com/s4wave/spacewave/sdk/bucket/lookup/lookup.proto

#include "lookup_srpc.pb.hpp"

namespace s4wave::bucket_lookup {

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::GetRef(const s4wave::bucket_lookup::GetRefRequest& in, s4wave::bucket_lookup::GetRefResponse* out) {
  return cc_->ExecCall(service_id_, "GetRef", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::FollowRef(const s4wave::bucket_lookup::FollowRefRequest& in, s4wave::bucket_lookup::FollowRefResponse* out) {
  return cc_->ExecCall(service_id_, "FollowRef", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::GetBlock(const s4wave::bucket_lookup::GetBlockRequest& in, s4wave::bucket_lookup::GetBlockResponse* out) {
  return cc_->ExecCall(service_id_, "GetBlock", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::PutBlock(const s4wave::bucket_lookup::PutBlockRequest& in, s4wave::bucket_lookup::PutBlockResponse* out) {
  return cc_->ExecCall(service_id_, "PutBlock", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::BuildTransaction(const s4wave::bucket_lookup::BuildTransactionRequest& in, s4wave::bucket_lookup::BuildTransactionResponse* out) {
  return cc_->ExecCall(service_id_, "BuildTransaction", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::BuildTransactionAtRef(const s4wave::bucket_lookup::BuildTransactionAtRefRequest& in, s4wave::bucket_lookup::BuildTransactionAtRefResponse* out) {
  return cc_->ExecCall(service_id_, "BuildTransactionAtRef", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::Clone(const s4wave::bucket_lookup::CloneRequest& in, s4wave::bucket_lookup::CloneResponse* out) {
  return cc_->ExecCall(service_id_, "Clone", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::Release(const s4wave::bucket_lookup::ReleaseRequest& in, s4wave::bucket_lookup::ReleaseResponse* out) {
  return cc_->ExecCall(service_id_, "Release", in, out);
}

starpc::Error SRPCBucketLookupCursorResourceServiceClientImpl::Unmarshal(const s4wave::bucket_lookup::UnmarshalRequest& in, s4wave::bucket_lookup::UnmarshalResponse* out) {
  return cc_->ExecCall(service_id_, "Unmarshal", in, out);
}

std::vector<std::string> SRPCBucketLookupCursorResourceServiceHandler::GetMethodIDs() const {
  return {
    "GetRef",
    "FollowRef",
    "GetBlock",
    "PutBlock",
    "BuildTransaction",
    "BuildTransactionAtRef",
    "Clone",
    "Release",
    "Unmarshal",
  };
}

std::pair<bool, starpc::Error> SRPCBucketLookupCursorResourceServiceHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "GetRef") {
    s4wave::bucket_lookup::GetRefRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::GetRefResponse resp;
    err = impl_->GetRef(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "FollowRef") {
    s4wave::bucket_lookup::FollowRefRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::FollowRefResponse resp;
    err = impl_->FollowRef(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "GetBlock") {
    s4wave::bucket_lookup::GetBlockRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::GetBlockResponse resp;
    err = impl_->GetBlock(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "PutBlock") {
    s4wave::bucket_lookup::PutBlockRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::PutBlockResponse resp;
    err = impl_->PutBlock(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "BuildTransaction") {
    s4wave::bucket_lookup::BuildTransactionRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::BuildTransactionResponse resp;
    err = impl_->BuildTransaction(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "BuildTransactionAtRef") {
    s4wave::bucket_lookup::BuildTransactionAtRefRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::BuildTransactionAtRefResponse resp;
    err = impl_->BuildTransactionAtRef(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Clone") {
    s4wave::bucket_lookup::CloneRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::CloneResponse resp;
    err = impl_->Clone(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Release") {
    s4wave::bucket_lookup::ReleaseRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::ReleaseResponse resp;
    err = impl_->Release(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  } else if (method_id == "Unmarshal") {
    s4wave::bucket_lookup::UnmarshalRequest req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    s4wave::bucket_lookup::UnmarshalResponse resp;
    err = impl_->Unmarshal(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace s4wave::bucket_lookup
