name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  member-ci:
    name: CI (${{ matrix.member.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        member:
          - name: auth
            build_script: ''
            check_script: ''
            lint_go_script: lint:go:auth
            lint_js_script: lint:js:auth
            test_go_script: test:go:auth
            test_js_script: test:js:auth
          - name: forge
            build_script: ''
            check_script: ''
            lint_go_script: lint:go:forge
            lint_js_script: lint:js:forge
            test_go_script: test:go:forge
            test_js_script: test:js:forge
          - name: net
            build_script: build:net
            check_script: ''
            lint_go_script: lint:go:net
            lint_js_script: lint:js:net
            test_go_script: test:go:net
            test_js_script: test:js:net
          - name: bldr
            build_script: ''
            check_script: bldr:typecheck
            lint_go_script: ''
            lint_js_script: ''
            test_go_script: ''
            test_js_script: ''
          - name: db
            build_script: ''
            check_script: ''
            lint_go_script: lint:go:db
            lint_js_script: lint:js:db
            test_go_script: test:go:db
            test_js_script: test:js:db
          - name: identity
            build_script: ''
            check_script: ''
            lint_go_script: lint:go:identity
            lint_js_script: lint:js:identity
            test_go_script: test:go:identity
            test_js_script: test:js:identity
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: oven-sh/setup-bun@v2

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Cache aptre tools
        uses: actions/cache@v5
        with:
          path: ./.tools
          key: ${{ runner.os }}-aptre-tools-${{ hashFiles('**/go.sum') }}

      - name: Build Javascript
        if: ${{ matrix.member.build_script != '' }}
        run: bun run ${{ matrix.member.build_script }}

      - name: Run member checks
        if: ${{ matrix.member.check_script != '' }}
        run: bun run ${{ matrix.member.check_script }}

      - name: Test Go
        if: ${{ matrix.member.test_go_script != '' }}
        run: bun run ${{ matrix.member.test_go_script }}

      - name: Test Js
        if: ${{ matrix.member.test_js_script != '' }}
        run: bun run ${{ matrix.member.test_js_script }}

      - name: Lint Js
        if: ${{ matrix.member.lint_js_script != '' }}
        run: bun run ${{ matrix.member.lint_js_script }}

      - name: Lint Go
        if: ${{ matrix.member.lint_go_script != '' }}
        run: bun run ${{ matrix.member.lint_go_script }}
